/*
 * Copyright (c) 2020, Zoinkwiz
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.questhelper.collections;

import lombok.Getter;
import net.runelite.api.gameval.NpcID;

import java.util.Arrays;
import java.util.List;

public class NpcCollections
{
	@Getter
	private static final List<Integer> cats = Arrays.asList(
		NpcID.LOSTKITTEN,
		NpcID.KITTENPET1,
		NpcID.KITTENPET_LIGHT,
		NpcID.KITTENPET_BROWN,
		NpcID.KITTENPET_BLACK,
		NpcID.KITTENPET_BROWNGREY,
		NpcID.KITTENPET_BLUEGREY,
		NpcID.GROWNCAT,
		NpcID.GROWNCAT_LIGHT,
		NpcID.GROWNCAT_BROWN,
		NpcID.GROWNCAT_BLACK,
		NpcID.GROWNCAT_BROWNGREY,
		NpcID.GROWNCAT_BLUEGREY,

		NpcID.MYQ3_CAT_01,
		NpcID.MYQ3_CAT_02,

		NpcID.POH_GROWNCAT_DEFAULT,
		NpcID.POH_GROWNCAT_LIGHT,
		NpcID.POH_GROWNCAT_BLACK,
		NpcID.POH_GROWNCAT_BLUEGREY,

		NpcID.LAZYCAT_LIGHT,
		NpcID.LAZYCAT,
		NpcID.LAZYCAT_BROWN,
		NpcID.LAZYCAT_BLACK,
		NpcID.LAZYCAT_BROWNGREY,
		NpcID.LAZYCAT_BLUEGREY,
		NpcID.POH_LAZYCAT_DEFAULT,
		NpcID.POH_LAZYCAT_LIGHT,
		NpcID.POH_LAZYCAT_BROWN,
		NpcID.POH_LAZYCAT_BLACK,
		NpcID.POH_LAZYCAT_BROWNGREY,
		NpcID.POH_LAZYCAT_BLUEGREY,
		NpcID.WILEYCAT_LIGHT,
		NpcID.WILEYCAT,
		NpcID.WILEYCAT_BROWN,
		NpcID.WILEYCAT_BLACK,
		NpcID.WILEYCAT_BROWNGREY,
		NpcID.WILEYCAT_BLUEGREY,

		NpcID.POH_WILEYCAT_DEFAULT,
		NpcID.POH_WILEYCAT_LIGHT,
		NpcID.POH_WILEYCAT_BROWN,
		NpcID.POH_WILEYCAT_BLACK,
		NpcID.POH_WILEYCAT_BROWNGREY,
		NpcID.POH_WILEYCAT_BLUEGREY,
		NpcID.KITTENPET_HELL,
		NpcID.KITTENPET_HELL,
		NpcID.GROWNCAT_HELL,
		NpcID.POH_GROWNCAT_HELL,
		NpcID.OVERGROWNCAT_HELL,
		NpcID.POH_OVERGROWNCAT_HELL,
		NpcID.LAZYCAT_HELL,
		NpcID.POH_LAZYCAT_HELL,
		NpcID.WILEYCAT_HELL,
		NpcID.POH_WILEYCAT_HELL
	);

	@Getter
	private static final List<Integer> huntingCats = Arrays.asList(
		NpcID.LOSTKITTEN,
		NpcID.KITTENPET1,
		NpcID.KITTENPET_LIGHT,
		NpcID.KITTENPET_BROWN,
		NpcID.KITTENPET_BLACK,
		NpcID.KITTENPET_BROWNGREY,
		NpcID.KITTENPET_BLUEGREY,
		NpcID.GROWNCAT,
		NpcID.GROWNCAT_LIGHT,
		NpcID.GROWNCAT_BROWN,
		NpcID.GROWNCAT_BLACK,
		NpcID.GROWNCAT_BROWNGREY,
		NpcID.GROWNCAT_BLUEGREY,
		NpcID.LAZYCAT_LIGHT,
		NpcID.LAZYCAT,
		NpcID.LAZYCAT_BROWN,
		NpcID.LAZYCAT_BLACK,
		NpcID.LAZYCAT_BROWNGREY,
		NpcID.LAZYCAT_BLUEGREY,
		NpcID.POH_LAZYCAT_DEFAULT,
		NpcID.POH_LAZYCAT_LIGHT,
		NpcID.POH_LAZYCAT_BROWN,
		NpcID.POH_LAZYCAT_BLACK,
		NpcID.POH_LAZYCAT_BROWNGREY,
		NpcID.POH_LAZYCAT_BLUEGREY,
		NpcID.WILEYCAT_LIGHT,
		NpcID.WILEYCAT,
		NpcID.WILEYCAT_BROWN,
		NpcID.WILEYCAT_BLACK,
		NpcID.WILEYCAT_BROWNGREY,
		NpcID.WILEYCAT_BLUEGREY,

		NpcID.POH_WILEYCAT_DEFAULT,
		NpcID.POH_WILEYCAT_LIGHT,
		NpcID.POH_WILEYCAT_BROWN,
		NpcID.POH_WILEYCAT_BLACK,
		NpcID.POH_WILEYCAT_BROWNGREY,
		NpcID.POH_WILEYCAT_BLUEGREY,
		NpcID.KITTENPET_HELL,
		NpcID.KITTENPET_HELL,
		NpcID.GROWNCAT_HELL,
		NpcID.POH_GROWNCAT_HELL,
		NpcID.LAZYCAT_HELL,
		NpcID.POH_LAZYCAT_HELL,
		NpcID.WILEYCAT_HELL,
		NpcID.POH_WILEYCAT_HELL
	);
}
