/*
 * Copyright (c) 2020, Zoinkwiz
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.questhelper;

import java.util.Arrays;
import java.util.List;
import lombok.Getter;
import net.runelite.api.NpcID;

public class NpcCollections
{
	@Getter
	private static final List<Integer> cats = Arrays.asList(
		NpcID.KITTEN,
		NpcID.KITTEN_5591,
		NpcID.KITTEN_5592,
		NpcID.KITTEN_5593,
		NpcID.KITTEN_5594,
		NpcID.KITTEN_5595,
		NpcID.KITTEN_5596,
		NpcID.CAT_1619,
		NpcID.CAT_1620,
		NpcID.CAT_1621,
		NpcID.CAT_1622,
		NpcID.CAT_1623,
		NpcID.CAT_1624,

		NpcID.CAT_3831,
		NpcID.CAT_3832,

		NpcID.CAT_6662,
		NpcID.CAT_6663,
		NpcID.CAT_6665,
		NpcID.CAT_6667,

		NpcID.LAZY_CAT,
		NpcID.LAZY_CAT_1627,
		NpcID.LAZY_CAT_1628,
		NpcID.LAZY_CAT_1629,
		NpcID.LAZY_CAT_1630,
		NpcID.LAZY_CAT_1631,
		NpcID.LAZY_CAT_6683,
		NpcID.LAZY_CAT_6684,
		NpcID.LAZY_CAT_6685,
		NpcID.LAZY_CAT_6686,
		NpcID.LAZY_CAT_6687,
		NpcID.LAZY_CAT_6688,
		NpcID.WILY_CAT,
		NpcID.WILY_CAT_5585,
		NpcID.WILY_CAT_5586,
		NpcID.WILY_CAT_5587,
		NpcID.WILY_CAT_5588,
		NpcID.WILY_CAT_5589,

		NpcID.WILY_CAT_6690,
		NpcID.WILY_CAT_6691,
		NpcID.WILY_CAT_6692,
		NpcID.WILY_CAT_6693,
		NpcID.WILY_CAT_6694,
		NpcID.WILY_CAT_6695,
		NpcID.HELLKITTEN,
		NpcID.HELLKITTEN,
		NpcID.HELLCAT,
		NpcID.HELLCAT_6668,
		NpcID.OVERGROWN_HELLCAT,
		NpcID.OVERGROWN_HELLCAT_6682,
		NpcID.LAZY_HELLCAT,
		NpcID.LAZY_HELLCAT_6689,
		NpcID.WILY_HELLCAT,
		NpcID.WILY_HELLCAT_6696
	);

	@Getter
	private static final List<Integer> huntingCats = Arrays.asList(
		NpcID.KITTEN,
		NpcID.KITTEN_5591,
		NpcID.KITTEN_5592,
		NpcID.KITTEN_5593,
		NpcID.KITTEN_5594,
		NpcID.KITTEN_5595,
		NpcID.KITTEN_5596,
		NpcID.CAT_1619,
		NpcID.CAT_1620,
		NpcID.CAT_1621,
		NpcID.CAT_1622,
		NpcID.CAT_1623,
		NpcID.CAT_1624,
		NpcID.LAZY_CAT,
		NpcID.LAZY_CAT_1627,
		NpcID.LAZY_CAT_1628,
		NpcID.LAZY_CAT_1629,
		NpcID.LAZY_CAT_1630,
		NpcID.LAZY_CAT_1631,
		NpcID.LAZY_CAT_6683,
		NpcID.LAZY_CAT_6684,
		NpcID.LAZY_CAT_6685,
		NpcID.LAZY_CAT_6686,
		NpcID.LAZY_CAT_6687,
		NpcID.LAZY_CAT_6688,
		NpcID.WILY_CAT,
		NpcID.WILY_CAT_5585,
		NpcID.WILY_CAT_5586,
		NpcID.WILY_CAT_5587,
		NpcID.WILY_CAT_5588,
		NpcID.WILY_CAT_5589,

		NpcID.WILY_CAT_6690,
		NpcID.WILY_CAT_6691,
		NpcID.WILY_CAT_6692,
		NpcID.WILY_CAT_6693,
		NpcID.WILY_CAT_6694,
		NpcID.WILY_CAT_6695,
		NpcID.HELLKITTEN,
		NpcID.HELLKITTEN,
		NpcID.HELLCAT,
		NpcID.HELLCAT_6668,
		NpcID.LAZY_HELLCAT,
		NpcID.LAZY_HELLCAT_6689,
		NpcID.WILY_HELLCAT,
		NpcID.WILY_HELLCAT_6696
	);
}