/*
 * Copyright (c) 2025, Zoinkwiz <https://github.com/Zoinkwiz>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.questhelper.helpers.mischelpers.roguetrader;

import java.util.ArrayList;
import java.util.List;

public class SudokuLayouts
{
    private static Integer WATER_RUNE = 1;
    private static Integer FIRE_RUNE = 2;
    private static Integer EARTH_RUNE = 3;
    private static Integer AIR_RUNE = 4;
    private static Integer MIND_RUNE = 5;
    private static Integer BODY_RUNE = 6;
    private static Integer LAW_RUNE = 7;
    private static Integer CHAOS_RUNE = 8;
    private static Integer DEATH_RUNE = 9;

    private static Integer[] SMALL_0 = new Integer[] {
            EARTH_RUNE, WATER_RUNE, AIR_RUNE, FIRE_RUNE,
            FIRE_RUNE, AIR_RUNE, WATER_RUNE, EARTH_RUNE,
            WATER_RUNE, FIRE_RUNE, EARTH_RUNE, AIR_RUNE,
            AIR_RUNE, EARTH_RUNE, FIRE_RUNE, WATER_RUNE
    };

    private static Integer[] SMALL_1 = new Integer[] {
            EARTH_RUNE, AIR_RUNE, WATER_RUNE, FIRE_RUNE,
            WATER_RUNE, FIRE_RUNE, EARTH_RUNE, AIR_RUNE,
            FIRE_RUNE, WATER_RUNE, AIR_RUNE, EARTH_RUNE,
            AIR_RUNE, EARTH_RUNE, FIRE_RUNE, WATER_RUNE
    };

    private static Integer[] SMALL_2 = new Integer[] {
            AIR_RUNE, EARTH_RUNE, WATER_RUNE, FIRE_RUNE,
            WATER_RUNE, FIRE_RUNE, AIR_RUNE, EARTH_RUNE,
            FIRE_RUNE, WATER_RUNE, EARTH_RUNE, AIR_RUNE,
            EARTH_RUNE, AIR_RUNE, FIRE_RUNE, WATER_RUNE
    };

    private static Integer[] SMALL_3 = new Integer[] {
            EARTH_RUNE, AIR_RUNE, FIRE_RUNE, WATER_RUNE,
            FIRE_RUNE, WATER_RUNE, AIR_RUNE, EARTH_RUNE,
            WATER_RUNE, FIRE_RUNE, EARTH_RUNE, AIR_RUNE,
            AIR_RUNE, EARTH_RUNE, WATER_RUNE, FIRE_RUNE
    };

    private static Integer[] SMALL_4 = new Integer[] {
            AIR_RUNE, EARTH_RUNE, WATER_RUNE, FIRE_RUNE,
            WATER_RUNE, FIRE_RUNE, EARTH_RUNE, AIR_RUNE,
            FIRE_RUNE, WATER_RUNE, AIR_RUNE, EARTH_RUNE,
            EARTH_RUNE, AIR_RUNE, FIRE_RUNE, WATER_RUNE
    };

    private static Integer[] SMALL_5 = new Integer[] {
            AIR_RUNE, EARTH_RUNE, FIRE_RUNE, WATER_RUNE,
            FIRE_RUNE, WATER_RUNE, AIR_RUNE, EARTH_RUNE,
            WATER_RUNE, FIRE_RUNE, EARTH_RUNE, AIR_RUNE,
            EARTH_RUNE, AIR_RUNE, WATER_RUNE, FIRE_RUNE
    };

    private static Integer[] SMALL_6 = new Integer[] {
            EARTH_RUNE, AIR_RUNE, WATER_RUNE, FIRE_RUNE,
            FIRE_RUNE, WATER_RUNE, AIR_RUNE, EARTH_RUNE,
            WATER_RUNE, FIRE_RUNE, EARTH_RUNE, AIR_RUNE,
            AIR_RUNE, EARTH_RUNE, FIRE_RUNE, WATER_RUNE
    };

    private static Integer[] SMALL_7 = new Integer[] {
            AIR_RUNE, FIRE_RUNE, WATER_RUNE, EARTH_RUNE,
            EARTH_RUNE, WATER_RUNE, AIR_RUNE, FIRE_RUNE,
            WATER_RUNE, EARTH_RUNE, FIRE_RUNE, AIR_RUNE,
            FIRE_RUNE, AIR_RUNE, EARTH_RUNE, WATER_RUNE
    };

    private static Integer[] SMALL_8 = new Integer[] {
            FIRE_RUNE, WATER_RUNE, AIR_RUNE, EARTH_RUNE,
            EARTH_RUNE, AIR_RUNE, WATER_RUNE, FIRE_RUNE,
            WATER_RUNE, EARTH_RUNE, FIRE_RUNE, AIR_RUNE,
            WATER_RUNE, EARTH_RUNE, FIRE_RUNE, AIR_RUNE,
            AIR_RUNE, FIRE_RUNE, EARTH_RUNE, WATER_RUNE
    };

    private static Integer[] SMALL_9 = new Integer[] {
            FIRE_RUNE, WATER_RUNE, AIR_RUNE, EARTH_RUNE,
            EARTH_RUNE, AIR_RUNE, WATER_RUNE, FIRE_RUNE,
            WATER_RUNE, EARTH_RUNE, FIRE_RUNE, AIR_RUNE,
            AIR_RUNE, FIRE_RUNE, EARTH_RUNE, WATER_RUNE
    };

    private static Integer[] SMALL_10 = new Integer[] {
            EARTH_RUNE, AIR_RUNE, WATER_RUNE, FIRE_RUNE,
            FIRE_RUNE, WATER_RUNE, AIR_RUNE, EARTH_RUNE,
            WATER_RUNE, FIRE_RUNE, EARTH_RUNE, AIR_RUNE,
            AIR_RUNE, EARTH_RUNE, FIRE_RUNE, WATER_RUNE
    };

    private static Integer[] LARGE_0 = new Integer[] {
            WATER_RUNE, FIRE_RUNE, EARTH_RUNE, AIR_RUNE, MIND_RUNE, BODY_RUNE, LAW_RUNE, CHAOS_RUNE, DEATH_RUNE,
            AIR_RUNE, MIND_RUNE, BODY_RUNE, LAW_RUNE, CHAOS_RUNE, DEATH_RUNE, WATER_RUNE, FIRE_RUNE, EARTH_RUNE,
            LAW_RUNE, CHAOS_RUNE, DEATH_RUNE, WATER_RUNE, FIRE_RUNE, EARTH_RUNE, AIR_RUNE, MIND_RUNE, BODY_RUNE,
            FIRE_RUNE, EARTH_RUNE, WATER_RUNE, MIND_RUNE, BODY_RUNE, AIR_RUNE, CHAOS_RUNE, DEATH_RUNE, LAW_RUNE,
            MIND_RUNE, BODY_RUNE, AIR_RUNE, CHAOS_RUNE, DEATH_RUNE, LAW_RUNE, FIRE_RUNE, EARTH_RUNE, WATER_RUNE,
            CHAOS_RUNE, DEATH_RUNE, LAW_RUNE, FIRE_RUNE, EARTH_RUNE, WATER_RUNE, MIND_RUNE, BODY_RUNE, AIR_RUNE,
            EARTH_RUNE, WATER_RUNE, FIRE_RUNE, BODY_RUNE, AIR_RUNE, MIND_RUNE, DEATH_RUNE, LAW_RUNE, CHAOS_RUNE,
            BODY_RUNE, AIR_RUNE, MIND_RUNE, DEATH_RUNE, LAW_RUNE, CHAOS_RUNE, EARTH_RUNE, WATER_RUNE, FIRE_RUNE,
            DEATH_RUNE, LAW_RUNE, CHAOS_RUNE, EARTH_RUNE, WATER_RUNE, FIRE_RUNE, BODY_RUNE, AIR_RUNE, MIND_RUNE
    };

    private static Integer[] LARGE_1 = new Integer[] {
            WATER_RUNE, DEATH_RUNE, MIND_RUNE, FIRE_RUNE, CHAOS_RUNE, BODY_RUNE, LAW_RUNE, AIR_RUNE, EARTH_RUNE,
            CHAOS_RUNE, AIR_RUNE, BODY_RUNE, WATER_RUNE, LAW_RUNE, EARTH_RUNE, DEATH_RUNE, MIND_RUNE, FIRE_RUNE,
            LAW_RUNE, EARTH_RUNE, FIRE_RUNE, AIR_RUNE, MIND_RUNE, DEATH_RUNE, BODY_RUNE, WATER_RUNE, CHAOS_RUNE,
            AIR_RUNE, CHAOS_RUNE, EARTH_RUNE, DEATH_RUNE, FIRE_RUNE, LAW_RUNE, WATER_RUNE, BODY_RUNE, MIND_RUNE,
            BODY_RUNE, LAW_RUNE, DEATH_RUNE, EARTH_RUNE, WATER_RUNE, MIND_RUNE, CHAOS_RUNE, FIRE_RUNE, AIR_RUNE,
            MIND_RUNE, FIRE_RUNE, WATER_RUNE, CHAOS_RUNE, BODY_RUNE, AIR_RUNE, EARTH_RUNE, DEATH_RUNE, LAW_RUNE,
            EARTH_RUNE, WATER_RUNE, AIR_RUNE, LAW_RUNE, DEATH_RUNE, FIRE_RUNE, MIND_RUNE, CHAOS_RUNE, BODY_RUNE,
            DEATH_RUNE, BODY_RUNE, LAW_RUNE, MIND_RUNE, AIR_RUNE, CHAOS_RUNE, FIRE_RUNE, EARTH_RUNE, WATER_RUNE,
            FIRE_RUNE, MIND_RUNE, CHAOS_RUNE, BODY_RUNE, EARTH_RUNE, WATER_RUNE, AIR_RUNE, LAW_RUNE, DEATH_RUNE
    };

    private static Integer[] LARGE_2 = new Integer[] {
            AIR_RUNE, FIRE_RUNE, DEATH_RUNE, WATER_RUNE, MIND_RUNE, BODY_RUNE, LAW_RUNE, EARTH_RUNE, CHAOS_RUNE,
            LAW_RUNE, MIND_RUNE, BODY_RUNE, FIRE_RUNE, CHAOS_RUNE, EARTH_RUNE, DEATH_RUNE, WATER_RUNE, AIR_RUNE,
            WATER_RUNE, CHAOS_RUNE, EARTH_RUNE, AIR_RUNE, DEATH_RUNE, LAW_RUNE, FIRE_RUNE, BODY_RUNE, MIND_RUNE,
            CHAOS_RUNE, BODY_RUNE, AIR_RUNE, DEATH_RUNE, FIRE_RUNE, WATER_RUNE, EARTH_RUNE, MIND_RUNE, LAW_RUNE,
            DEATH_RUNE, WATER_RUNE, LAW_RUNE, MIND_RUNE, EARTH_RUNE, AIR_RUNE, CHAOS_RUNE, FIRE_RUNE, BODY_RUNE,
            MIND_RUNE, EARTH_RUNE, FIRE_RUNE, BODY_RUNE, LAW_RUNE, CHAOS_RUNE, AIR_RUNE, DEATH_RUNE, WATER_RUNE,
            EARTH_RUNE, AIR_RUNE, MIND_RUNE, LAW_RUNE, BODY_RUNE, FIRE_RUNE, WATER_RUNE, CHAOS_RUNE, DEATH_RUNE,
            FIRE_RUNE, DEATH_RUNE, WATER_RUNE, CHAOS_RUNE, AIR_RUNE, MIND_RUNE, BODY_RUNE, LAW_RUNE, EARTH_RUNE,
            BODY_RUNE, LAW_RUNE, CHAOS_RUNE, EARTH_RUNE, WATER_RUNE, DEATH_RUNE, MIND_RUNE, AIR_RUNE, FIRE_RUNE
    };

    private static Integer[] LARGE_3 = new Integer[] {
            WATER_RUNE, FIRE_RUNE, EARTH_RUNE, AIR_RUNE, MIND_RUNE, BODY_RUNE, LAW_RUNE, CHAOS_RUNE, DEATH_RUNE,
            AIR_RUNE, MIND_RUNE, BODY_RUNE, LAW_RUNE, CHAOS_RUNE, DEATH_RUNE, WATER_RUNE, FIRE_RUNE, EARTH_RUNE,
            LAW_RUNE, CHAOS_RUNE, DEATH_RUNE, WATER_RUNE, FIRE_RUNE, EARTH_RUNE, AIR_RUNE, MIND_RUNE, BODY_RUNE,
            FIRE_RUNE, EARTH_RUNE, WATER_RUNE, MIND_RUNE, BODY_RUNE, AIR_RUNE, CHAOS_RUNE, DEATH_RUNE, LAW_RUNE,
            MIND_RUNE, BODY_RUNE, AIR_RUNE, CHAOS_RUNE, DEATH_RUNE, LAW_RUNE, FIRE_RUNE, EARTH_RUNE, WATER_RUNE,
            CHAOS_RUNE, DEATH_RUNE, LAW_RUNE, FIRE_RUNE, EARTH_RUNE, WATER_RUNE, MIND_RUNE, BODY_RUNE, AIR_RUNE,
            EARTH_RUNE, WATER_RUNE, FIRE_RUNE, BODY_RUNE, AIR_RUNE, MIND_RUNE, DEATH_RUNE, LAW_RUNE, CHAOS_RUNE,
            BODY_RUNE, AIR_RUNE, MIND_RUNE, DEATH_RUNE, LAW_RUNE, CHAOS_RUNE, EARTH_RUNE, WATER_RUNE, FIRE_RUNE,
            DEATH_RUNE, LAW_RUNE, CHAOS_RUNE, EARTH_RUNE, WATER_RUNE, FIRE_RUNE, BODY_RUNE, AIR_RUNE, MIND_RUNE
    };

    private static Integer[] LARGE_4 = new Integer[] {
            LAW_RUNE, WATER_RUNE, DEATH_RUNE, EARTH_RUNE, FIRE_RUNE, BODY_RUNE, MIND_RUNE, CHAOS_RUNE, AIR_RUNE,
            FIRE_RUNE, BODY_RUNE, MIND_RUNE, CHAOS_RUNE, AIR_RUNE, LAW_RUNE, WATER_RUNE, DEATH_RUNE, EARTH_RUNE,
            AIR_RUNE, EARTH_RUNE, CHAOS_RUNE, DEATH_RUNE, WATER_RUNE, MIND_RUNE, BODY_RUNE, FIRE_RUNE, LAW_RUNE,
            MIND_RUNE, CHAOS_RUNE, AIR_RUNE, FIRE_RUNE, LAW_RUNE, EARTH_RUNE, DEATH_RUNE, BODY_RUNE, WATER_RUNE,
            DEATH_RUNE, LAW_RUNE, BODY_RUNE, MIND_RUNE, CHAOS_RUNE, WATER_RUNE, EARTH_RUNE, AIR_RUNE, FIRE_RUNE,
            EARTH_RUNE, FIRE_RUNE, WATER_RUNE, BODY_RUNE, DEATH_RUNE, AIR_RUNE, LAW_RUNE, MIND_RUNE, CHAOS_RUNE,
            BODY_RUNE, AIR_RUNE, LAW_RUNE, WATER_RUNE, MIND_RUNE, FIRE_RUNE, CHAOS_RUNE, EARTH_RUNE, DEATH_RUNE,
            WATER_RUNE, DEATH_RUNE, EARTH_RUNE, AIR_RUNE, BODY_RUNE, CHAOS_RUNE, FIRE_RUNE, LAW_RUNE, MIND_RUNE,
            CHAOS_RUNE, MIND_RUNE, FIRE_RUNE, LAW_RUNE, EARTH_RUNE, DEATH_RUNE, AIR_RUNE, WATER_RUNE, BODY_RUNE
    };

    private static Integer[] LARGE_5 = new Integer[] {
            EARTH_RUNE, AIR_RUNE, LAW_RUNE, WATER_RUNE, FIRE_RUNE, CHAOS_RUNE, BODY_RUNE, MIND_RUNE, DEATH_RUNE,
            CHAOS_RUNE, BODY_RUNE, MIND_RUNE, DEATH_RUNE, AIR_RUNE, LAW_RUNE, WATER_RUNE, FIRE_RUNE, EARTH_RUNE,
            DEATH_RUNE, WATER_RUNE, FIRE_RUNE, MIND_RUNE, EARTH_RUNE, BODY_RUNE, LAW_RUNE, CHAOS_RUNE, AIR_RUNE,
            LAW_RUNE, EARTH_RUNE, CHAOS_RUNE, FIRE_RUNE, DEATH_RUNE, MIND_RUNE, AIR_RUNE, WATER_RUNE, BODY_RUNE,
            AIR_RUNE, DEATH_RUNE, BODY_RUNE, CHAOS_RUNE, WATER_RUNE, EARTH_RUNE, MIND_RUNE, LAW_RUNE, FIRE_RUNE,
            FIRE_RUNE, MIND_RUNE, WATER_RUNE, BODY_RUNE, LAW_RUNE, AIR_RUNE, EARTH_RUNE, DEATH_RUNE, CHAOS_RUNE,
            WATER_RUNE, LAW_RUNE, AIR_RUNE, EARTH_RUNE, CHAOS_RUNE, DEATH_RUNE, FIRE_RUNE, BODY_RUNE, MIND_RUNE,
            BODY_RUNE, FIRE_RUNE, DEATH_RUNE, AIR_RUNE, MIND_RUNE, WATER_RUNE, CHAOS_RUNE, EARTH_RUNE, LAW_RUNE,
            MIND_RUNE, CHAOS_RUNE, EARTH_RUNE, LAW_RUNE, BODY_RUNE, FIRE_RUNE, DEATH_RUNE, AIR_RUNE, WATER_RUNE
    };

    private static Integer[] LARGE_6 = new Integer[] {
            BODY_RUNE, AIR_RUNE, CHAOS_RUNE, MIND_RUNE, FIRE_RUNE, EARTH_RUNE, LAW_RUNE, WATER_RUNE, DEATH_RUNE,
            WATER_RUNE, DEATH_RUNE, FIRE_RUNE, BODY_RUNE, AIR_RUNE, LAW_RUNE, MIND_RUNE, CHAOS_RUNE, EARTH_RUNE,
            EARTH_RUNE, LAW_RUNE, MIND_RUNE, WATER_RUNE, DEATH_RUNE, CHAOS_RUNE, AIR_RUNE, BODY_RUNE, FIRE_RUNE,
            MIND_RUNE, EARTH_RUNE, AIR_RUNE, DEATH_RUNE, CHAOS_RUNE, BODY_RUNE, FIRE_RUNE, LAW_RUNE, WATER_RUNE,
            LAW_RUNE, FIRE_RUNE, WATER_RUNE, AIR_RUNE, EARTH_RUNE, MIND_RUNE, BODY_RUNE, DEATH_RUNE, CHAOS_RUNE,
            CHAOS_RUNE, BODY_RUNE, DEATH_RUNE, LAW_RUNE, WATER_RUNE, FIRE_RUNE, EARTH_RUNE, MIND_RUNE, AIR_RUNE,
            AIR_RUNE, CHAOS_RUNE, BODY_RUNE, EARTH_RUNE, MIND_RUNE, DEATH_RUNE, WATER_RUNE, FIRE_RUNE, LAW_RUNE,
            FIRE_RUNE, WATER_RUNE, LAW_RUNE, CHAOS_RUNE, BODY_RUNE, AIR_RUNE, DEATH_RUNE, EARTH_RUNE, MIND_RUNE,
            DEATH_RUNE, MIND_RUNE, EARTH_RUNE, FIRE_RUNE, LAW_RUNE, WATER_RUNE, CHAOS_RUNE, AIR_RUNE, BODY_RUNE
    };

    private static Integer[] LARGE_7 = new Integer[] {
            MIND_RUNE, BODY_RUNE, EARTH_RUNE, LAW_RUNE, DEATH_RUNE, FIRE_RUNE, AIR_RUNE, WATER_RUNE, CHAOS_RUNE,
            AIR_RUNE, DEATH_RUNE, WATER_RUNE, MIND_RUNE, BODY_RUNE, CHAOS_RUNE, EARTH_RUNE, FIRE_RUNE, LAW_RUNE,
            CHAOS_RUNE, LAW_RUNE, FIRE_RUNE, WATER_RUNE, AIR_RUNE, EARTH_RUNE, DEATH_RUNE, MIND_RUNE, BODY_RUNE,
            DEATH_RUNE, CHAOS_RUNE, LAW_RUNE, BODY_RUNE, FIRE_RUNE, MIND_RUNE, WATER_RUNE, AIR_RUNE, EARTH_RUNE,
            WATER_RUNE, MIND_RUNE, BODY_RUNE, DEATH_RUNE, EARTH_RUNE, AIR_RUNE, CHAOS_RUNE, LAW_RUNE, FIRE_RUNE,
            EARTH_RUNE, FIRE_RUNE, AIR_RUNE, CHAOS_RUNE, WATER_RUNE, LAW_RUNE, BODY_RUNE, DEATH_RUNE, MIND_RUNE,
            LAW_RUNE, EARTH_RUNE, DEATH_RUNE, FIRE_RUNE, CHAOS_RUNE, WATER_RUNE, MIND_RUNE, BODY_RUNE, AIR_RUNE,
            BODY_RUNE, AIR_RUNE, MIND_RUNE, EARTH_RUNE, LAW_RUNE, DEATH_RUNE, FIRE_RUNE, CHAOS_RUNE, WATER_RUNE,
            FIRE_RUNE, WATER_RUNE, CHAOS_RUNE, AIR_RUNE, MIND_RUNE, BODY_RUNE, LAW_RUNE, EARTH_RUNE, DEATH_RUNE
    };

    private static Integer[] LARGE_8 = new Integer[] {
            DEATH_RUNE, AIR_RUNE, MIND_RUNE, FIRE_RUNE, EARTH_RUNE, WATER_RUNE, LAW_RUNE, BODY_RUNE, CHAOS_RUNE,
            CHAOS_RUNE, BODY_RUNE, FIRE_RUNE, LAW_RUNE, MIND_RUNE, DEATH_RUNE, WATER_RUNE, EARTH_RUNE, AIR_RUNE,
            EARTH_RUNE, LAW_RUNE, WATER_RUNE, BODY_RUNE, AIR_RUNE, CHAOS_RUNE, FIRE_RUNE, DEATH_RUNE, MIND_RUNE,
            AIR_RUNE, FIRE_RUNE, CHAOS_RUNE, DEATH_RUNE, BODY_RUNE, LAW_RUNE, EARTH_RUNE, MIND_RUNE, WATER_RUNE,
            WATER_RUNE, EARTH_RUNE, DEATH_RUNE, CHAOS_RUNE, FIRE_RUNE, MIND_RUNE, BODY_RUNE, AIR_RUNE, LAW_RUNE,
            LAW_RUNE, MIND_RUNE, BODY_RUNE, EARTH_RUNE, WATER_RUNE, AIR_RUNE, DEATH_RUNE, CHAOS_RUNE, FIRE_RUNE,
            FIRE_RUNE, WATER_RUNE, AIR_RUNE, MIND_RUNE, DEATH_RUNE, EARTH_RUNE, CHAOS_RUNE, LAW_RUNE, BODY_RUNE,
            MIND_RUNE, CHAOS_RUNE, EARTH_RUNE, WATER_RUNE, LAW_RUNE, BODY_RUNE, AIR_RUNE, FIRE_RUNE, DEATH_RUNE,
            BODY_RUNE, DEATH_RUNE, LAW_RUNE, AIR_RUNE, CHAOS_RUNE, FIRE_RUNE, MIND_RUNE, WATER_RUNE, EARTH_RUNE
    };


    private static Integer[] LARGE_9 = new Integer[] {
            MIND_RUNE, CHAOS_RUNE, BODY_RUNE, FIRE_RUNE, DEATH_RUNE, LAW_RUNE, EARTH_RUNE, WATER_RUNE, AIR_RUNE,
            LAW_RUNE, WATER_RUNE, EARTH_RUNE, BODY_RUNE, CHAOS_RUNE, AIR_RUNE, MIND_RUNE, DEATH_RUNE, FIRE_RUNE,
            FIRE_RUNE, AIR_RUNE, DEATH_RUNE, WATER_RUNE, EARTH_RUNE, MIND_RUNE, BODY_RUNE, LAW_RUNE, CHAOS_RUNE,
            DEATH_RUNE, FIRE_RUNE, LAW_RUNE, CHAOS_RUNE, MIND_RUNE, EARTH_RUNE, AIR_RUNE, BODY_RUNE, WATER_RUNE,
            WATER_RUNE, EARTH_RUNE, AIR_RUNE, LAW_RUNE, FIRE_RUNE, BODY_RUNE, CHAOS_RUNE, MIND_RUNE, DEATH_RUNE,
            CHAOS_RUNE, BODY_RUNE, MIND_RUNE, AIR_RUNE, WATER_RUNE, DEATH_RUNE, FIRE_RUNE, EARTH_RUNE, LAW_RUNE,
            AIR_RUNE, DEATH_RUNE, WATER_RUNE, EARTH_RUNE, BODY_RUNE, FIRE_RUNE, LAW_RUNE, CHAOS_RUNE, MIND_RUNE,
            EARTH_RUNE, MIND_RUNE, FIRE_RUNE, DEATH_RUNE, LAW_RUNE, CHAOS_RUNE, WATER_RUNE, AIR_RUNE, BODY_RUNE,
            BODY_RUNE, LAW_RUNE, CHAOS_RUNE, MIND_RUNE, AIR_RUNE, WATER_RUNE, DEATH_RUNE, FIRE_RUNE, EARTH_RUNE
    };

    private static Integer[] LARGE_10 = new Integer[] {
            BODY_RUNE, CHAOS_RUNE, LAW_RUNE, FIRE_RUNE, AIR_RUNE, DEATH_RUNE, WATER_RUNE, MIND_RUNE, EARTH_RUNE,
            MIND_RUNE, AIR_RUNE, FIRE_RUNE, WATER_RUNE, EARTH_RUNE, BODY_RUNE, CHAOS_RUNE, LAW_RUNE, DEATH_RUNE,
            EARTH_RUNE, WATER_RUNE, DEATH_RUNE, LAW_RUNE, MIND_RUNE, CHAOS_RUNE, AIR_RUNE, BODY_RUNE, FIRE_RUNE,
            FIRE_RUNE, DEATH_RUNE, MIND_RUNE, BODY_RUNE, CHAOS_RUNE, WATER_RUNE, EARTH_RUNE, AIR_RUNE, LAW_RUNE,
            LAW_RUNE, EARTH_RUNE, WATER_RUNE, MIND_RUNE, FIRE_RUNE, AIR_RUNE, DEATH_RUNE, CHAOS_RUNE, BODY_RUNE,
            CHAOS_RUNE, BODY_RUNE, AIR_RUNE, EARTH_RUNE, DEATH_RUNE, LAW_RUNE, FIRE_RUNE, WATER_RUNE, MIND_RUNE,
            AIR_RUNE, MIND_RUNE, EARTH_RUNE, CHAOS_RUNE, BODY_RUNE, FIRE_RUNE, LAW_RUNE, DEATH_RUNE, WATER_RUNE,
            DEATH_RUNE, LAW_RUNE, BODY_RUNE, AIR_RUNE, WATER_RUNE, EARTH_RUNE, MIND_RUNE, FIRE_RUNE, CHAOS_RUNE,
            WATER_RUNE, FIRE_RUNE, CHAOS_RUNE, DEATH_RUNE, LAW_RUNE, MIND_RUNE, BODY_RUNE, EARTH_RUNE, AIR_RUNE
    };
    private static final List<Integer[]> puzzlesSmall = new ArrayList<>(List.of(SMALL_0, SMALL_1, SMALL_2, SMALL_3, SMALL_4, SMALL_5, SMALL_6, SMALL_7, SMALL_8,
        SMALL_9, SMALL_10));
    private static final List<Integer[]> puzzlesLarge = new ArrayList<>(List.of(LARGE_0, LARGE_1, LARGE_2, LARGE_3, LARGE_4, LARGE_5, LARGE_6, LARGE_7, LARGE_8, LARGE_9, LARGE_10));
    public static final List<List<Integer[]>> puzzles = new ArrayList<>(List.of(puzzlesSmall, puzzlesLarge));
}
