/*
 *
 *  * Copyright (c) 2025, TTvanWillegen
 *  * All rights reserved.
 *  *
 *  * Redistribution and use in source and binary forms, with or without
 *  * modification, are permitted provided that the following conditions are met:
 *  *
 *  * 1. Redistributions of source code must retain the above copyright notice, this
 *  *    list of conditions and the following disclaimer.
 *  * 2. Redistributions in binary form must reproduce the above copyright notice,
 *  *    this list of conditions and the following disclaimer in the documentation
 *  *    and/or other materials provided with the distribution.
 *  *
 *  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *  * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *  * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 *  * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *  * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 *  * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *  * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
package com.questhelper.requirements.util;

import com.questhelper.requirements.zone.Zone;
import lombok.AllArgsConstructor;
import lombok.Getter;
import net.runelite.api.coords.WorldPoint;
import net.runelite.api.gameval.ObjectID;

@AllArgsConstructor
@Getter
public enum Port
{
	PORT_SARIM(0, "Port Sarim", ObjectID.SAILING_DOCKING_BUOY_PORT_SARIM, new WorldPoint(3048, 3186, 0), new Zone(new WorldPoint(3045, 3183, 0), new WorldPoint(3061, 3208, 0)), new WorldPoint(3051, 3193, 0), new WorldPoint(3028, 3194, 0), ObjectID.PORT_TASK_BOARD_PORT_SARIM, new WorldPoint(3030, 3197, 0))
	, PANDEMONIUM(1, "the Pandemonium", ObjectID.SAILING_DOCKING_BUOY_THE_PANDEMONIUM, new WorldPoint(3069, 2981, 0), new Zone(new WorldPoint(3065, 2974, 0), new WorldPoint(3084, 2998, 0)), new WorldPoint(3070, 2987, 0), new WorldPoint(3061,2985, 0), ObjectID.PORT_TASK_BOARD_PANDEMONIUM, new WorldPoint(3058, 2958, 0))
//	, LANDS_END(2, "Land's End", ObjectID.SAILING_DOCKING_BUOY_LANDS_END, null, null, null, null, ObjectID.PORT_TASK_BOARD_LANDS_END, null)
	, MUSA_POINT(3, "Musa Point", ObjectID.SAILING_DOCKING_BUOY_MUSA_POINT, new WorldPoint(2961, 3152, 0), new Zone(new WorldPoint(2974, 3156, 0), new WorldPoint(2956, 3144, 0)), new WorldPoint(2961, 3146, 0), new WorldPoint(2952, 3150, 0), ObjectID.PORT_TASK_BOARD_MUSA_POINT, new WorldPoint(2956, 3144, 0))
//	, HOSIDIUS(4, "Hosidius", ObjectID.SAILING_DOCKING_BUOY_HOSIDIUS, null, null, null, null, ObjectID.PORT_TASK_BOARD_HOSIDIUS, null)
//	, PORT_PISCARILIUS(-1, "Port Piscarilius", ObjectID.SAILING_DOCKING_BUOY_PORT_PISCARILIUS, null, null, null, null, ObjectID.PORT_TASK_BOARD_PORT_PISCARILIUS, null)
//	, RIMMINGTON(-1, "Rimmington", ObjectID.SAILING_DOCKING_BUOY_RIMMINGTON, null, null, null, null, -1, null)
//	, CATHERBY(-1, "Catherby", ObjectID.SAILING_DOCKING_BUOY_CATHERBY, null, null, null, null, ObjectID.PORT_TASK_BOARD_CATHERBY, null)
	;


	private final int id;
	private final String name;
	private final int buoyId;
	private final WorldPoint buoyLocation;
	private final Zone dockZone;
	private final WorldPoint gangplankLocation; // Relevant ObjectIDs: SAILING_GANGPLANK_DISEMBARK, SAILING_GANGPLANK_EMBARK, SAILING_MOORING_DISEMBARK, SAILING_MOORING_EMBARK;
	private final WorldPoint ledgerTableLocation; // Relevant ObjectIDs: DOCK_LOADING_BAY_LEDGER_TABLE_WITHDRAW, DOCK_LOADING_BAY_LEDGER_TABLE_DEPOSIT;
	private final int portTaskBoardId;
	private final WorldPoint portTaskBoardLocation; // Relevant ObjectIDs: DOCK_LOADING_BAY_LEDGER_TABLE_WITHDRAW, DOCK_LOADING_BAY_LEDGER_TABLE_DEPOSIT;
}
//	SAILING_DOCKING_BUOY_BRIMHAVEN = 59777;
//  PORT_TASK_BOARD_BRIMHAVEN = 60298;
//	SAILING_DOCKING_BUOY_ARDOUGNE = 59778;
//  PORT_TASK_BOARD_ARDOUGNE = 60297;

//	SAILING_DOCKING_BUOY_PORT_KHAZARD = 59779;
//  PORT_TASK_BOARD_PORT_KHAZARD = 60290;

//	SAILING_DOCKING_BUOY_WITCHAVEN = 59780;
//	SAILING_DOCKING_BUOY_ENTRANA = 59781;

//	SAILING_DOCKING_BUOY_CIVITAS_ILLA_FORTIS = 59782;
//  PORT_TASK_BOARD_CIVITAS_ILLA_FORTIS = 60294;

//	SAILING_DOCKING_BUOY_CORSAIR_COVE = 59783;
//  PORT_TASK_BOARD_CORSAIR_COVE = 60299;

//	SAILING_DOCKING_BUOY_CAIRN_ISLE = 59784;
//	SAILING_DOCKING_BUOY_SUNSET_COAST = 59785;

//	SAILING_DOCKING_BUOY_THE_SUMMER_SHORE = 59786;
//  PORT_TASK_BOARD_THE_SUMMER_SHORE = 60300;

//	SAILING_DOCKING_BUOY_ALDARIN = 59787;
//  PORT_TASK_BOARD_ALDARIN = 60301;

//	SAILING_DOCKING_BUOY_RUINS_OF_UNKAH = 59788;
//  PORT_TASK_BOARD_RUINS_OF_UNKAH = 60291;

//	SAILING_DOCKING_BUOY_VOID_KNIGHTS_OUTPOST = 59789;
//  PORT_TASK_BOARD_VOID_KNIGHTS_OUTPOST = 60302;

//	SAILING_DOCKING_BUOY_PORT_ROBERTS = 59790;
//  PORT_TASK_BOARD_PORT_ROBERTS = 60303;

//	SAILING_DOCKING_BUOY_RED_ROCK = 59791;
//  PORT_TASK_BOARD_RED_ROCK = 60304;

//	SAILING_DOCKING_BUOY_RELLEKKA = 59792;
//  PORT_TASK_BOARD_RELLEKKA = 60292;

//	SAILING_DOCKING_BUOY_ETCETERIA = 59793;
//  PORT_TASK_BOARD_ETCETERIA = 60305;

//	SAILING_DOCKING_BUOY_PORT_TYRAS = 59794;
//  PORT_TASK_BOARD_PORT_TYRAS = 60306;

//	SAILING_DOCKING_BUOY_DEEPFIN_POINT = 59795;
//  PORT_TASK_BOARD_DEEPFIN_POINT = 60307;

//	SAILING_DOCKING_BUOY_JATIZSO = 59796;
//	SAILING_DOCKING_BUOY_NEITIZNOT = 59797;

//	SAILING_DOCKING_BUOY_PRIFDDINAS = 59798;
//  PORT_TASK_BOARD_PRIFDDINAS = 60308;

//	SAILING_DOCKING_BUOY_PISCATORIS = 59799;

//	SAILING_DOCKING_BUOY_LUNAR_ISLE = 59800;
//  PORT_TASK_BOARD_LUNAR_ISLE = 60309;

//	SAILING_DOCKING_BUOY_ISLE_OF_SOULS = 59801;
//	SAILING_DOCKING_BUOY_WATERBIRTH_ISLAND = 59802;
//	SAILING_DOCKING_BUOY_WEISS = 59803;
//	SAILING_DOCKING_BUOY_DOGNOSE_ISLAND = 59804;
//	SAILING_DOCKING_BUOY_REMOTE_ISLAND = 59805;
//	SAILING_DOCKING_BUOY_THE_LITTLE_PEARL = 59806;
//	SAILING_DOCKING_BUOY_THE_ONYX_CREST = 59807;
//	SAILING_DOCKING_BUOY_LAST_LIGHT = 59808;
//	SAILING_DOCKING_BUOY_CHARRED_ISLAND = 59809;
//	SAILING_DOCKING_BUOY_VATRACHOS_ISLAND = 59810;
//	SAILING_DOCKING_BUOY_ANGLERS_RETREAT = 59811;
//	SAILING_DOCKING_BUOY_MINOTAURS_REST = 59812;
//	SAILING_DOCKING_BUOY_ISLE_OF_BONES = 59813;
//	SAILING_DOCKING_BUOY_TEAR_OF_THE_SOUL = 59814;
//	SAILING_DOCKING_BUOY_WINTUMBER_ISLAND = 59815;
//	SAILING_DOCKING_BUOY_THE_CROWN_JEWEL = 59816;
//	SAILING_DOCKING_BUOY_RAINBOWS_END = 59817;
//	SAILING_DOCKING_BUOY_SUNBLEAK_ISLAND = 59818;
//	SAILING_DOCKING_BUOY_SHIMMERING_ATOLL = 59819;
//	SAILING_DOCKING_BUOY_LAGUNA_AURORAE = 59820;
//	SAILING_DOCKING_BUOY_CHINCHOMPA_ISLAND = 59821;
//	SAILING_DOCKING_BUOY_LLEDRITH_ISLAND = 59822;
//	SAILING_DOCKING_BUOY_YNYSDAIL = 59823;
//	SAILING_DOCKING_BUOY_BUCCANEERS_HAVEN = 59824;
//	SAILING_DOCKING_BUOY_DRUMSTICK_ISLE = 59825;
//	SAILING_DOCKING_BUOY_BRITTLE_ISLE = 59826;
//	SAILING_DOCKING_BUOY_GRIMSTONE = 59827;