//package com.questhelper.maker;
//
//import com.questhelper.panel.PanelDetails;
//import com.questhelper.questhelpers.ComplexStateQuestHelper;
//import com.questhelper.requirements.item.ItemRequirement;
//import com.questhelper.requirements.player.SkillRequirement;
//import com.questhelper.requirements.conditional.Conditions;
//import static com.questhelper.requirements.util.LogicHelper.not;
//import static com.questhelper.requirements.util.LogicHelper.nor;
//import com.questhelper.requirements.util.LogicType;
//import com.questhelper.requirements.util.Operation;
//import com.questhelper.requirements.ManualRequirement;
//import com.questhelper.requirements.var.VarbitRequirement;
//import com.questhelper.steps.ConditionalStep;
//import com.questhelper.steps.DetailedQuestStep;
//import com.questhelper.steps.NpcStep;
//import com.questhelper.steps.ObjectStep;
//import com.questhelper.steps.QuestStep;
//import java.util.ArrayList;
//import java.util.List;
//import net.runelite.api.coords.WorldPoint;
//import net.runelite.api.Skill;
//import com.questhelper.requirements.zone.Zone;
//import com.questhelper.requirements.zone.ZoneRequirement;
//
//public class GeneratedQuestHelper extends ComplexStateQuestHelper
//{
//	// Captured requirements
//	ItemRequirement bucket;
//	ItemRequirement pot;
//	ItemRequirement rake;
//	ItemRequirement uncutRuby;
//	ItemRequirement cake;
//	ItemRequirement knife;
//	ItemRequirement chisel;
//	ItemRequirement coins;
//	ItemRequirement whiteApron;
//	ItemRequirement greenCape;
//	ItemRequirement bones;
//	ItemRequirement grain;
//	ItemRequirement bucketOfWater;
//	ItemRequirement dramenStaff;
//	ItemRequirement grapeBarrel;
//	ItemRequirement sapphire;
//	ItemRequirement emerald;
//	ItemRequirement ruby;
//	ItemRequirement rawRabbit;
//	ItemRequirement cookedRabbit;
//	ItemRequirement bigFishingNet;
//	ItemRequirement moonLite;
//	ItemRequirement jugOfWine;
//	ItemRequirement stew;
//	ItemRequirement ironMace;
//	ItemRequirement bronzeAxe;
//	ItemRequirement logs;
//	ItemRequirement needle;
//	ItemRequirement thread;
//	ItemRequirement cowhide;
//	ItemRequirement leather;
//	ItemRequirement wool;
//	ItemRequirement flax;
//
//	// Captured steps
//	DetailedQuestStep openleaguesmenu;
//	DetailedQuestStep completeleaguestutorial;
//	DetailedQuestStep togglerunenergy;
//	NpcStep pickpocketcitizen;
//	NpcStep petrenu;
//	DetailedQuestStep bownearrenu;
//	ObjectStep usewaterpump;
//	NpcStep talktoportmaster;
//	ObjectStep zanarisfairyring;
//	NpcStep crynearachild;
//	ObjectStep stealcakesfrombakersstall;
//	NpcStep tradeshopkeeper;
//	NpcStep attackratlevel1;
//	DetailedQuestStep salutequoatlos;
//	ObjectStep useprayernearshrineofralos;
//	NpcStep petxolo;
//	ObjectStep drinkfrombirdbath;
//	ObjectStep chopdowntree;
//	NpcStep tradefloria;
//	DetailedQuestStep burnlog;
//	DetailedQuestStep fletchlog;
//	ObjectStep attackdummy;
//	NpcStep useeastcivitasbank;
//	NpcStep talktogladiator;
//	NpcStep talktotradercrewmember;
//	ObjectStep usefurnace;
//	DetailedQuestStep blowglassintooillanterns;
//	NpcStep depositmoltenglass;
//	NpcStep attackchickenlevel1;
//	ObjectStep picksweetcorn;
//	ObjectStep pickandeatonion;
//	ObjectStep pickwheat;
//	ObjectStep fillhopper;
//	ObjectStep emptyflourbin;
//	ObjectStep pickpotato;
//	NpcStep tradeharminia;
//	ObjectStep rakeflowerpatch;
//	ObjectStep milkdairybuffalo;
//	NpcStep shearalpaca;
//	NpcStep tradeartima;
//	NpcStep travelwithrenu;
//	DetailedQuestStep hometeleport;
//	DetailedQuestStep returntocivitas;
//	NpcStep feedbonestomolossus;
//	NpcStep talktovineyardforeman;
//	NpcStep returntovineyardforeman;
//	NpcStep withdrawaldarinbanker;
//	NpcStep tradetoci;
//	DetailedQuestStep cutextragems;
//	NpcStep travelbackwithrenu;
//	DetailedQuestStep claimfirstrelic;
//	DetailedQuestStep equipapronandgreencape;
//	NpcStep useeastcivitasbankagain;
//	NpcStep depositoillanterns;
//	ObjectStep pickcabbage;
//	DetailedQuestStep emptywaterbucket;
//	NpcStep attackcowlevel2;
//	DetailedQuestStep burybones;
//	ObjectStep aldarinfairyring;
//	DetailedQuestStep collectshimmeringgrapes;
//	NpcStep attackseagulllevel2;
//	NpcStep tradechartership;
//	ObjectStep cookrabbitonoven;
//	DetailedQuestStep eatcookedrabbit;
//	NpcStep talktoantonia;
//	ObjectStep fillabucketwithsand;
//	NpcStep talktopicaria;
//	NpcStep chartertocivitas;
//	NpcStep castfishingspot;
//	NpcStep talktobartender;
//	DetailedQuestStep drinkmoonlite;
//	DetailedQuestStep drinkjugofwine;
//	NpcStep pickpocketcitizenuntilsuccess;
//	NpcStep tradesilkmerchant;
//	NpcStep givestewtooli;
//	NpcStep buypoh;
//	NpcStep buyironmace;
//	NpcStep traveltoauburnvale;
//	NpcStep tradesebamo;
//	NpcStep tradelunami;
//	NpcStep depositinauburnvale;
//	DetailedQuestStep equipironmace;
//	ObjectStep chopdowndeadtree;
//	NpcStep makeplankatsawmill;
//	NpcStep tradeauburnvaleshopkeeper;
//	NpcStep tanleatheratchouani;
//	DetailedQuestStep craftleatherchaps;
//	ObjectStep admirebeautifullog;
//	ObjectStep steponenttrail;
//	ObjectStep pickflax;
//	ObjectStep spinflaxandwool;
//	ManualRequirement orderManual_b4774b5043644e3d;
//	ManualRequirement orderManual_e1bd7473bf70454e;
//	ManualRequirement orderManual_3742c1b9593940d1;
//	ManualRequirement orderManual_d874440fd5d64f29;
//	ManualRequirement orderManual_3e3dee13c7f04f7e;
//	ManualRequirement orderManual_561cc210c13940ac;
//	ManualRequirement orderManual_6231965cb7364873;
//	ManualRequirement orderManual_ef2a1f04f2344ffa;
//	ManualRequirement orderManual_bcef081ee50848c4;
//	ManualRequirement orderManual_b6371840b279439e;
//	ManualRequirement orderManual_33caa0d56cbf4e3a;
//	ManualRequirement orderManual_23938df7e41444d2;
//	ManualRequirement orderManual_e3d64188fe2c4386;
//	ManualRequirement orderManual_0643bdd0fc574df9;
//	ManualRequirement orderManual_b3170a80123940bc;
//	ManualRequirement orderManual_b4898e48afbc4790;
//	ManualRequirement orderManual_4ed627e87870495c;
//	ManualRequirement orderManual_c6d823de02b04365;
//	ManualRequirement orderManual_925b2750606e45aa;
//	ManualRequirement orderManual_7307d7a1545249c7;
//	ManualRequirement orderManual_03a02189ef2c41c9;
//	ManualRequirement orderManual_f959773416174f78;
//	ManualRequirement orderManual_20f2b6f2760b4291;
//	ManualRequirement orderManual_7e7d7d1aa70f4206;
//	ManualRequirement orderManual_956b7e8f1cba43e0;
//	ManualRequirement orderManual_397839f1b1f24846;
//	ManualRequirement orderManual_00554878070f4f0e;
//	ManualRequirement orderManual_d30aa746056444c3;
//	ManualRequirement orderManual_c75f7a1c32ef4f3f;
//	ManualRequirement orderManual_7060fc9ca3444a25;
//	ManualRequirement orderManual_b4066f8970574c8a;
//	ManualRequirement orderManual_04453a244b8e4e28;
//	ManualRequirement orderManual_2a4533618e3843cc;
//	ManualRequirement orderManual_864a7b35392e4bb5;
//	ManualRequirement orderManual_b1d18d00302b44e1;
//	ManualRequirement orderManual_39b2b856b31b46a8;
//	ManualRequirement orderManual_bd0d9307875d4407;
//	ManualRequirement orderManual_eab67f10eb07403e;
//	ManualRequirement orderManual_9b1eca8dccbd42d2;
//	ManualRequirement orderManual_a695d187db0d426b;
//	ManualRequirement orderManual_defad039d9094571;
//	ManualRequirement orderManual_52df5d410a9c4609;
//	ManualRequirement orderManual_71753357153f4aea;
//	ManualRequirement orderManual_2d00f499fa504f2c;
//	ManualRequirement orderManual_3a1994fd479f4789;
//	ManualRequirement orderManual_d54c4bcf9b4a4242;
//	ManualRequirement orderManual_2db5a3f19d944160;
//	ManualRequirement orderManual_fc2cc76a69004247;
//	ManualRequirement orderManual_98baa1e71c7749f8;
//	ManualRequirement orderManual_4aa9260549cf41b7;
//	ManualRequirement orderManual_dfe5b2e820144145;
//	ManualRequirement orderManual_b30a9b21a43c4399;
//	ManualRequirement orderManual_558232d615c64c3e;
//	ManualRequirement orderManual_b9bdb796f67b407a;
//	ManualRequirement orderManual_8bc30c12632a4f04;
//	ManualRequirement orderManual_18df7577e9814dd7;
//	ManualRequirement orderManual_6ec91f1a29aa464f;
//	ManualRequirement orderManual_03d13e43583345cb;
//	ManualRequirement orderManual_a1a431788a17478e;
//	ManualRequirement orderManual_e2c6f51feb6142eb;
//	ConditionalStep section1Task;
//	ConditionalStep section2Task;
//	ConditionalStep section3Task;
//	ConditionalStep section4Task;
//	ConditionalStep section5Task;
//
//	@Override
//	protected void setupRequirements()
//	{
//		bucket = new ItemRequirement("Bucket", 1925);
//		pot = new ItemRequirement("Pot", 1931);
//		rake = new ItemRequirement("Rake", 0);
//		uncutRuby = new ItemRequirement("Uncut Ruby", 0);
//		cake = new ItemRequirement("Cake", 1891);
//		knife = new ItemRequirement("Knife", 946);
//		chisel = new ItemRequirement("Chisel", 1755);
//		coins = new ItemRequirement("Coins", 995);
//		whiteApron = new ItemRequirement("White apron", 1005);
//		greenCape = new ItemRequirement("Green cape", 1027);
//		bones = new ItemRequirement("Bones", 526);
//		grain = new ItemRequirement("Grain", 1947);
//		bucketOfWater = new ItemRequirement("Bucket of water", 1929);
//		dramenStaff = new ItemRequirement("Dramen Staff", 772);
//		grapeBarrel = new ItemRequirement("Grape barrel", 30037);
//		sapphire = new ItemRequirement("Sapphire", 1607);
//		emerald = new ItemRequirement("Emerald", 1605);
//		ruby = new ItemRequirement("Ruby", 1603);
//		rawRabbit = new ItemRequirement("Raw rabbit", 3226);
//		cookedRabbit = new ItemRequirement("Cooked rabbit", 3228);
//		bigFishingNet = new ItemRequirement("Big fishing net", 305);
//		moonLite = new ItemRequirement("Moon-lite", 29418);
//		jugOfWine = new ItemRequirement("Jug of wine", 1993);
//		stew = new ItemRequirement("Stew", 2003);
//		ironMace = new ItemRequirement("Iron mace", 1420);
//		bronzeAxe = new ItemRequirement("Bronze axe", 1351);
//		logs = new ItemRequirement("Logs", 1511);
//		needle = new ItemRequirement("Needle", 1733);
//		thread = new ItemRequirement("Thread", 1734);
//		cowhide = new ItemRequirement("Cowhide", 1739);
//		leather = new ItemRequirement("Leather", 1741);
//		wool = new ItemRequirement("Wool", 1737);
//		flax = new ItemRequirement("Flax", 1779);
//	}
//
//	private void setupSteps()
//	{
//		// Section: Civitas illa Fortis [show when true: no condition]
//		openleaguesmenu = new DetailedQuestStep(this, "Open the Leagues Menu.");
//		completeleaguestutorial = new DetailedQuestStep(this, "Complete the Leagues Tutorial.");
//		claimfirstrelic = new DetailedQuestStep(this, "Claim your first relic! If choosing Endless Harvest, turn off the auto-banking feature for now.");
//		togglerunenergy = new DetailedQuestStep(this, "Turn run energy off and then back on.");
//		pickpocketcitizen = new NpcStep(this, new int[]{13198, 13197, 13195}, new WorldPoint(1687, 3135, 0), "Pickpocket a citizen until level 5 thieving.", true);
//		petrenu = new NpcStep(this, 13350, new WorldPoint(1697, 3142, 0), "Run east and pet Renu.", true);
//		bownearrenu = new DetailedQuestStep(this, new WorldPoint(1697, 3140, 0), "Use the Bow emote near Renu.");
//		travelwithrenu = new NpcStep(this, 13350, new WorldPoint(1697, 3142, 0), "Travel with Renu to the Sunset Coast.", true);
//		travelbackwithrenu = new NpcStep(this, 13350, new WorldPoint(1548, 2997, 0), "Travel with Renu back to Civitas illa Fortis.", true);
//		usewaterpump = new ObjectStep(this, 52646, new WorldPoint(1690, 3132, 0), "Fill a bucket at the water pump.", true);
//		usewaterpump.addRequirement(bucket.highlighted());
//		attackdummy = new ObjectStep(this, 52645, new WorldPoint(1659, 3148, 0), "Attack Dummy.", true);
//		crynearachild = new NpcStep(this, 13188, new WorldPoint(1674, 3109, 0), "Use the Cry emote near a child.", true);
//		stealcakesfrombakersstall = new ObjectStep(this, 51937, new WorldPoint(1688, 3111, 0), "Thieve 14+ cakes from the Cake Stall.", true);
//		{
//			SkillRequirement sr = new SkillRequirement(Skill.THIEVING, 5, true);
//			stealcakesfrombakersstall.addRequirement(sr);
//		}
//		tradeshopkeeper = new NpcStep(this, 13330, new WorldPoint(1670, 3123, 0), "Sell your cakes to the shopkeeper (sell 1 to maximize gp!). Buy 1 chisel and 1 knife.", true);
//		tradeshopkeeper.addRequirement(cake);
//		tradefloria = new NpcStep(this, 13340, new WorldPoint(1659, 3100, 0), "Buy 1 Pink Skirt, 1 Brown Apron, and 1 Green Cape.", true);
//		equipapronandgreencape = new DetailedQuestStep(this, "Equip the items you purchased.");
//		equipapronandgreencape.addRequirement(greenCape.highlighted());
//		equipapronandgreencape.addRequirement(whiteApron.highlighted());
//		attackratlevel1 = new NpcStep(this, 2854, new WorldPoint(1655, 3084, 0), "Kill a rat with a bow.", true);
//		salutequoatlos = new DetailedQuestStep(this, new WorldPoint(1699, 3083, 0), "Use the Salute emote near the statue of Quoatlos.");
//		useprayernearshrineofralos = new ObjectStep(this, 52405, new WorldPoint(1701, 3085, 0), "Activate the Thick Skin prayer while standing next to the altar.", true);
//		petxolo = new NpcStep(this, 12996, new WorldPoint(1709, 3088, 0), "Pet Xolo.", true);
//		drinkfrombirdbath = new ObjectStep(this, 52394, new WorldPoint(1713, 3086, 0), "Drink-from Bird bath.", true);
//		chopdowntree = new ObjectStep(this, 52823, new WorldPoint(1707, 3090, 0), "Chop 2 logs from a nearby Tree.", true);
//		burnlog = new DetailedQuestStep(this, "Burn a log.");
//		fletchlog = new DetailedQuestStep(this, "Fletch a log into arrow shafts.");
//		useeastcivitasbank = new NpcStep(this, 13219, new WorldPoint(1779, 3092, 0), "Deposit everything, withdraw coins, chisel, dramen staff (equipped), pot, and bucket of water.", true);
//		tradeartima = new NpcStep(this, 13342, new WorldPoint(1767, 3103, 0), "Buy shears and a glassblowing pipe from Artima.", true);
//		talktogladiator = new NpcStep(this, 12841, new WorldPoint(1802, 9523, 0), "Talk-to Gladiator.", true);
//		talktoportmaster = new NpcStep(this, 15470, new WorldPoint(1781, 3144, 0), "Talk-to Port master.", true);
//		talktotradercrewmember = new NpcStep(this, 9334, new WorldPoint(1743, 3135, 0), "Buy 10 buckets of sand, 10 soda ash.", true);
//		usefurnace = new ObjectStep(this, 50698, new WorldPoint(1769, 3111, 0), "Make 10 molten glass.", true);
//		depositmoltenglass = new NpcStep(this, 13219, new WorldPoint(1779, 3092, 0), "Deposit 10 molten glass into the bank.", true);
//		blowglassintooillanterns = new DetailedQuestStep(this, "Blow 10 molten glass into oil lanterns.");
//		depositoillanterns = new NpcStep(this, 13219, new WorldPoint(1779, 3092, 0), "Deposit the 10 oil lanterns.", true);
//		// Section: Outer Fortis [show when true: no condition]
//		pickcabbage = new ObjectStep(this, 1161, new WorldPoint(1742, 3059, 0), "Pick (and drop) 6 cabbages.", true);
//		attackchickenlevel1 = new NpcStep(this, new int[]{1174, 1173}, new WorldPoint(1740, 3053, 0), "Kill a chicken and pick up its bones.", true);
//		feedbonestomolossus = new NpcStep(this, 12993, new WorldPoint(1702, 3063, 0), "Feed some bones to Molossus.", true);
//		feedbonestomolossus.addRequirement(bones.highlighted());
//		picksweetcorn = new ObjectStep(this, 51829, new WorldPoint(1717, 3051, 0), "Pick sweetcorn.", true).addAlternateObjects(51830);
//		pickandeatonion = new ObjectStep(this, 51837, new WorldPoint(1702, 3048, 0), "Pick an onion and eat it.", true).addAlternateObjects(51838);
//		pickwheat = new ObjectStep(this, 15506, new WorldPoint(1679, 3048, 0), "Pick 6 wheat.", true).addAlternateObjects(15507);
//		fillhopper = new ObjectStep(this, 52591, new WorldPoint(1653, 3046, 2), "Fill the hopper and use the controls until you are out of grain.", true).addAlternateObjects(52592);
//		fillhopper.addRequirement(grain.quantity(6).highlighted());
//		emptyflourbin = new ObjectStep(this, 52999, new WorldPoint(1655, 3045, 0), "Empty Flour bin.", true);
//		emptyflourbin.addRequirement(pot.highlighted());
//		pickpotato = new ObjectStep(this, 312, new WorldPoint(1595, 3080, 0), "Pick (and drop) 6 potatoes.", true);
//		tradeharminia = new NpcStep(this, 12766, new WorldPoint(1585, 3105, 0), "Buy a rake from Harminia.", true);
//		rakeflowerpatch = new ObjectStep(this, 50693, new WorldPoint(1585, 3098, 0), "Rake Flower Patch.", true);
//		emptywaterbucket = new DetailedQuestStep(this, "Empty the bucket of water.");
//		emptywaterbucket.addRequirement(bucketOfWater.highlighted());
//		milkdairybuffalo = new ObjectStep(this, 52576, new WorldPoint(1588, 3119, 0), "Milk Dairy Buffalo.", true);
//		shearalpaca = new NpcStep(this, new int[]{12986, 12988}, new WorldPoint(1565, 3120, 0), "Shear Alpaca.", true);
//		zanarisfairyring = new ObjectStep(this, 29495, new WorldPoint(1651, 3010, 0), "Take the Fairy Ring to Zanaris.", true);
//		zanarisfairyring.addRequirement(dramenStaff.highlighted());
//		attackcowlevel2 = new NpcStep(this, 5842, new WorldPoint(2432, 4446, 0), "Kill a Cow  (level-2), pick up the bones and cowhide.", true);
//		burybones = new DetailedQuestStep(this, "Bury the Bones.");
//		burybones.addRequirement(bones.highlighted());
//		aldarinfairyring = new ObjectStep(this, 29560, new WorldPoint(2412, 4434, 0), "Take the Fairy Ring to Aldarin (CKQ).", true);
//		aldarinfairyring.addRequirement(dramenStaff);
//		talktovineyardforeman = new NpcStep(this, 13908, new WorldPoint(1370, 2915, 0), "Talk-to Vineyard foreman.", true);
//		collectshimmeringgrapes = new DetailedQuestStep(this, "Collect 4 shimmering grapes from the nearby vineyards (Vineyard Helper plugin can help if you have trouble identifying the shimmering grapes).");
//		collectshimmeringgrapes.addRequirement(grapeBarrel);
//		returntovineyardforeman = new NpcStep(this, 13908, new WorldPoint(1370, 2915, 0), "Return to the Vineyard foreman with a filled grape barrel.", true);
//		returntovineyardforeman.addRequirement(grapeBarrel);
//		withdrawaldarinbanker = new NpcStep(this, 13225, new WorldPoint(1401, 2928, 0), "Deposit everything and withdraw coins and chisel.", true);
//		tradetoci = new NpcStep(this, 13915, new WorldPoint(1428, 2975, 0), "Buy, cut, and sell gems until you have more than a 50k gp cash stack.", true);
//		cutextragems = new DetailedQuestStep(this, "Cut three extra of each gem and save them for later.");
//		attackseagulllevel2 = new NpcStep(this, 1338, new WorldPoint(1439, 2967, 0), "Kill a Seagull  (level-2).", true);
//		tradechartership = new NpcStep(this, new int[]{9358, 9322}, new WorldPoint(1454, 2969, 0), "Buy 5 raw rabbit, a tyras helm, and a bucket from the nearby Charter Ship.", true);
//		cookrabbitonoven = new ObjectStep(this, 52647, new WorldPoint(1433, 2962, 0), "Cook the rabbit on the oven until you burn one and cook one successfully.", true);
//		cookrabbitonoven.addRequirement(rawRabbit.quantity(5).highlighted());
//		eatcookedrabbit = new DetailedQuestStep(this, "Eat the Cooked rabbit.");
//		eatcookedrabbit.addRequirement(cookedRabbit.highlighted());
//		// Section: Sunset Coast [show when true: no condition]
//		talktoantonia = new NpcStep(this, 13985, new WorldPoint(1441, 2978, 0), "Travel with Antonia to the Sunset Coast.", true);
//		talktoantonia.addRequirement(coins.quantity(20));
//		fillabucketwithsand = new ObjectStep(this, 50733, new WorldPoint(1520, 3001, 0), "Fill a bucket with sand on the Sunset Coast.", true);
//		fillabucketwithsand.addRequirement(bucket.highlighted());
//		talktopicaria = new NpcStep(this, 13158, new WorldPoint(1560, 2962, 0), "Buy 1000 feathers and 1 big fishing net from the fishing store southeast of the Sunset Coast.", true);
//		talktopicaria.addRequirement(coins.quantity(2020));
//		// Section: Civitas illa Fortis [show when true: no condition]
//		chartertocivitas = new NpcStep(this, new int[]{9358, 9322}, new WorldPoint(1515, 2972, 0), "Charter a ship to Civitas illa Fortis.", true);
//		chartertocivitas.addRequirement(coins.quantity(250));
//		buyironmace = new NpcStep(this, 13333, new WorldPoint(1773, 3059, 0), "Purchase an iron mace from the Mace Shop southeast of Civitas illa Fortis.", true);
//		buyironmace.addRequirement(coins.quantity(81));
//		equipironmace = new DetailedQuestStep(this, "Equip the Iron mace.");
//		equipironmace.addRequirement(ironMace);
//		castfishingspot = new NpcStep(this, 13329, new WorldPoint(1738, 3101, 0), "Fish at the fishing spot in the park until you have caught 1 casket, 1 boot, and 1 house key.", true);
//		castfishingspot.addRequirement(bigFishingNet.highlighted());
//		talktobartender = new NpcStep(this, 13344, new WorldPoint(1711, 3116, 0), "Buy 1 cup of tea, 1 Moon-lite, 1 stew, and 1 jug of wine from the nearby bar.", true);
//		talktobartender.addRequirement(coins.quantity(46));
//		drinkmoonlite = new DetailedQuestStep(this, "Drink the Moon-lite.");
//		drinkmoonlite.addRequirement(moonLite);
//		drinkjugofwine = new DetailedQuestStep(this, "Drink the Jug of wine.");
//		drinkjugofwine.addRequirement(jugOfWine);
//		pickpocketcitizenuntilsuccess = new NpcStep(this, new int[]{13179, 13185}, new WorldPoint(1707, 3110, 0), "Pickpocket a Citizen until you have been successful 10 times in a row without failure.", true);
//		buypoh = new NpcStep(this, 13343, new WorldPoint(1705, 3100, 0), "Purchase a Player-owned House from the Estate Agent.", true);
//		buypoh.addRequirement(coins.quantity(1000));
//		tradesilkmerchant = new NpcStep(this, 13334, new WorldPoint(1675, 3112, 0), "Buy silk and then sell it back to the Silk Merchant.", true);
//		tradesilkmerchant.addRequirement(coins.quantity(15));
//		givestewtooli = new NpcStep(this, 13318, new WorldPoint(1653, 3105, 0), "Give some stew to Oli near the east Civitas illa Fortis bank.", true);
//		givestewtooli.addRequirement(stew.highlighted());
//		// Section: Auburnvale [show when true: no condition]
//		traveltoauburnvale = new NpcStep(this, 13350, new WorldPoint(1697, 3142, 0), "Travel with Renu to Auburnvale.", true);
//		depositinauburnvale = new NpcStep(this, 14671, new WorldPoint(1415, 3353, 0), "Deposit everything, withdraw coins, cowhide, wool, and bronze axe.", true);
//		tradesebamo = new NpcStep(this, 14658, new WorldPoint(1410, 3345, 0), "Buy an Air Staff from the staff shop.", true);
//		tradesebamo.addRequirement(coins.quantity(1500));
//		tradelunami = new NpcStep(this, 14657, new WorldPoint(1402, 3344, 0), "Buy a Steel, Mith, and Adamant axe from the axe shop.", true);
//		tradelunami.addRequirement(coins.quantity(2000));
//		chopdowndeadtree = new ObjectStep(this, 1289, new WorldPoint(1406, 3331, 0), "Chop down a Dead tree from the river south of the Auburnvale bank.", true);
//		chopdowndeadtree.addRequirement(bronzeAxe);
//		makeplankatsawmill = new NpcStep(this, 14659, new WorldPoint(1395, 3369, 0), "Buy a normal plank from the Sawmill Operator.", true);
//		makeplankatsawmill.addRequirement(logs);
//		makeplankatsawmill.addRequirement(coins.quantity(100));
//		tanleatheratchouani = new NpcStep(this, 14662, new WorldPoint(1369, 3357, 0), "Talk-to Chouani to tan your cowhide into soft leather.", true);
//		tanleatheratchouani.addRequirement(cowhide);
//		tanleatheratchouani.addRequirement(coins.quantity(2));
//		tradeauburnvaleshopkeeper = new NpcStep(this, 14656, new WorldPoint(1379, 3352, 0), "Buy a needle and thread from the Auburnvale General Store.", true);
//		tradeauburnvaleshopkeeper.addRequirement(coins.quantity(2));
//		craftleatherchaps = new DetailedQuestStep(this, "Use Needle on Leather with Thread in your inventory to make Leather Chaps.");
//		craftleatherchaps.addRequirement(leather.highlighted());
//		craftleatherchaps.addRequirement(needle.highlighted());
//		craftleatherchaps.addRequirement(thread);
//		admirebeautifullog = new ObjectStep(this, 57112, new WorldPoint(1382, 3348, 0), "Admire Beautiful log.", true);
//		steponenttrail = new ObjectStep(this, 57115, new WorldPoint(1395, 3340, 0), "Step on two nearby Ent Trails created behind a walking Ent.", true).addAlternateObjects(57116);
//		pickflax = new ObjectStep(this, 14896, new WorldPoint(1372, 3320, 0), "Pick 6 flax in the Nemus Retreat.", true);
//		spinflaxandwool = new ObjectStep(this, 55330, new WorldPoint(1373, 3314, 0), "Spin 1 ball of wool and 1 bowstring.", true);
//		spinflaxandwool.addRequirement(wool);
//		spinflaxandwool.addRequirement(flax);
//		hometeleport = new DetailedQuestStep(this, "Use the Home Teleport spell.");
//		returntocivitas = new DetailedQuestStep(this, "Exit Yama's Lair to Civitas illa Fortis.");
//		orderManual_b4774b5043644e3d = new ManualRequirement();
//		orderManual_e1bd7473bf70454e = new ManualRequirement();
//		orderManual_3742c1b9593940d1 = new ManualRequirement();
//		orderManual_d874440fd5d64f29 = new ManualRequirement();
//		orderManual_3e3dee13c7f04f7e = new ManualRequirement();
//		orderManual_561cc210c13940ac = new ManualRequirement();
//		orderManual_6231965cb7364873 = new ManualRequirement();
//		orderManual_ef2a1f04f2344ffa = new ManualRequirement();
//		orderManual_bcef081ee50848c4 = new ManualRequirement();
//		orderManual_b6371840b279439e = new ManualRequirement();
//		orderManual_33caa0d56cbf4e3a = new ManualRequirement();
//		orderManual_23938df7e41444d2 = new ManualRequirement();
//		orderManual_e3d64188fe2c4386 = new ManualRequirement();
//		orderManual_0643bdd0fc574df9 = new ManualRequirement();
//		orderManual_b3170a80123940bc = new ManualRequirement();
//		orderManual_b4898e48afbc4790 = new ManualRequirement();
//		orderManual_4ed627e87870495c = new ManualRequirement();
//		orderManual_c6d823de02b04365 = new ManualRequirement();
//		orderManual_925b2750606e45aa = new ManualRequirement();
//		orderManual_7307d7a1545249c7 = new ManualRequirement();
//		orderManual_03a02189ef2c41c9 = new ManualRequirement();
//		orderManual_f959773416174f78 = new ManualRequirement();
//		orderManual_20f2b6f2760b4291 = new ManualRequirement();
//		orderManual_7e7d7d1aa70f4206 = new ManualRequirement();
//		orderManual_956b7e8f1cba43e0 = new ManualRequirement();
//		orderManual_397839f1b1f24846 = new ManualRequirement();
//		orderManual_00554878070f4f0e = new ManualRequirement();
//		orderManual_d30aa746056444c3 = new ManualRequirement();
//		orderManual_c75f7a1c32ef4f3f = new ManualRequirement();
//		orderManual_7060fc9ca3444a25 = new ManualRequirement();
//		orderManual_b4066f8970574c8a = new ManualRequirement();
//		orderManual_04453a244b8e4e28 = new ManualRequirement();
//		orderManual_2a4533618e3843cc = new ManualRequirement();
//		orderManual_864a7b35392e4bb5 = new ManualRequirement();
//		orderManual_b1d18d00302b44e1 = new ManualRequirement();
//		orderManual_39b2b856b31b46a8 = new ManualRequirement();
//		orderManual_bd0d9307875d4407 = new ManualRequirement();
//		orderManual_eab67f10eb07403e = new ManualRequirement();
//		orderManual_9b1eca8dccbd42d2 = new ManualRequirement();
//		orderManual_a695d187db0d426b = new ManualRequirement();
//		orderManual_defad039d9094571 = new ManualRequirement();
//		orderManual_52df5d410a9c4609 = new ManualRequirement();
//		orderManual_71753357153f4aea = new ManualRequirement();
//		orderManual_2d00f499fa504f2c = new ManualRequirement();
//		orderManual_3a1994fd479f4789 = new ManualRequirement();
//		orderManual_d54c4bcf9b4a4242 = new ManualRequirement();
//		orderManual_2db5a3f19d944160 = new ManualRequirement();
//		orderManual_fc2cc76a69004247 = new ManualRequirement();
//		orderManual_98baa1e71c7749f8 = new ManualRequirement();
//		orderManual_4aa9260549cf41b7 = new ManualRequirement();
//		orderManual_dfe5b2e820144145 = new ManualRequirement();
//		orderManual_b30a9b21a43c4399 = new ManualRequirement();
//		orderManual_558232d615c64c3e = new ManualRequirement();
//		orderManual_b9bdb796f67b407a = new ManualRequirement();
//		orderManual_8bc30c12632a4f04 = new ManualRequirement();
//		orderManual_18df7577e9814dd7 = new ManualRequirement();
//		orderManual_6ec91f1a29aa464f = new ManualRequirement();
//		orderManual_03d13e43583345cb = new ManualRequirement();
//		orderManual_a1a431788a17478e = new ManualRequirement();
//		orderManual_e2c6f51feb6142eb = new ManualRequirement();
//	}
//
//	@Override
//	public QuestStep loadStep()
//	{
//		initializeRequirements();
//		setupSteps();
//
//		section1Task = new ConditionalStep(this, depositoillanterns);
//		section1Task.addStep(not(new VarbitRequirement(14662, Operation.EQUAL, 1, "Open the Leagues Menu")), openleaguesmenu);
//		section1Task.addStep(not(new VarbitRequirement(14445, Operation.EQUAL, 1, "Complete the Leagues Tutorial")), completeleaguestutorial);
//		section1Task.addStep(not(orderManual_b4774b5043644e3d), claimfirstrelic);
//		section1Task.addStep(not(new VarbitRequirement(14668, Operation.EQUAL, 1, "Turn off your run")), togglerunenergy);
//		section1Task.addStep(not(new VarbitRequirement(14733, Operation.EQUAL, 1, "Achieve Your First Level 5")), pickpocketcitizen);
//		section1Task.addStep(not(new VarbitRequirement(14493, Operation.EQUAL, 1, "Pet Renu")), petrenu);
//		section1Task.addStep(not(orderManual_e1bd7473bf70454e), bownearrenu);
//		section1Task.addStep(not(orderManual_3742c1b9593940d1), travelwithrenu);
//		section1Task.addStep(not(orderManual_d874440fd5d64f29), travelbackwithrenu);
//		section1Task.addStep(not(orderManual_3e3dee13c7f04f7e), usewaterpump);
//		section1Task.addStep(not(new VarbitRequirement(14441, Operation.EQUAL, 1, "Attack a dummy")), attackdummy);
//		section1Task.addStep(not(new VarbitRequirement(14528, Operation.EQUAL, 1, "Cry near a child")), crynearachild);
//		section1Task.addStep(not(orderManual_561cc210c13940ac), stealcakesfrombakersstall);
//		section1Task.addStep(not(orderManual_6231965cb7364873), tradeshopkeeper);
//		section1Task.addStep(not(orderManual_ef2a1f04f2344ffa), tradefloria);
//		section1Task.addStep(not(new Conditions(LogicType.OR, new VarbitRequirement(14260, Operation.EQUAL, 1, "Equip 3 unique Echo Items"), new VarbitRequirement(14261, Operation.EQUAL, 1, "Equip 2 unique Echo Items"))), equipapronandgreencape);
//		section1Task.addStep(not(new VarbitRequirement(13906, Operation.EQUAL, 1, "Defeat a Rat")), attackratlevel1);
//		section1Task.addStep(not(new VarbitRequirement(14504, Operation.EQUAL, 1, "Salute next to a statue of Quoatlos")), salutequoatlos);
//		section1Task.addStep(not(new VarbitRequirement(13530, Operation.EQUAL, 1, "Activate a prayer near an altar")), useprayernearshrineofralos);
//		section1Task.addStep(not(new VarbitRequirement(14495, Operation.EQUAL, 1, "Pet Xolo in Civitas")), petxolo);
//		section1Task.addStep(not(new VarbitRequirement(14531, Operation.EQUAL, 1, "Drink from a bird bath")), drinkfrombirdbath);
//		section1Task.addStep(not(new Conditions(LogicType.OR, new VarbitRequirement(14777, Operation.EQUAL, 1, "Chop 100 Willow Logs"), new VarbitRequirement(14778, Operation.EQUAL, 1, "Chop 100 Yew Logs"), new VarbitRequirement(14779, Operation.EQUAL, 1, "Chop 75 Magic Logs"), new VarbitRequirement(14780, Operation.EQUAL, 1, "Chop Some Logs"))), chopdowntree);
//		section1Task.addStep(not(orderManual_bcef081ee50848c4), burnlog);
//		section1Task.addStep(not(new Conditions(LogicType.OR, new VarbitRequirement(14857, Operation.EQUAL, 1, "Fletch 200 Magic Longbow (u)"), new VarbitRequirement(14860, Operation.EQUAL, 1, "Fletch 50 Willow longbow (u)"), new VarbitRequirement(15075, Operation.EQUAL, 1, "Obtain 50 Million Fletching XP"), new VarbitRequirement(15322, Operation.EQUAL, 1, "Smith 150 Iron Arrowtips"))), fletchlog);
//		section1Task.addStep(not(orderManual_b6371840b279439e), useeastcivitasbank);
//		section1Task.addStep(not(orderManual_33caa0d56cbf4e3a), tradeartima);
//		section1Task.addStep(not(new VarbitRequirement(14511, Operation.EQUAL, 1, "Talk to a Gladiator")), talktogladiator);
//		section1Task.addStep(not(new VarbitRequirement(14666, Operation.EQUAL, 1, "Talk to any Port master")), talktoportmaster);
//		section1Task.addStep(not(orderManual_23938df7e41444d2), talktotradercrewmember);
//		section1Task.addStep(not(orderManual_e3d64188fe2c4386), usefurnace);
//		section1Task.addStep(not(orderManual_0643bdd0fc574df9), depositmoltenglass);
//		section1Task.addStep(not(orderManual_b3170a80123940bc), talktotradercrewmember);
//		section1Task.addStep(not(orderManual_b4898e48afbc4790), usefurnace);
//		section1Task.addStep(not(orderManual_4ed627e87870495c), blowglassintooillanterns);
//
//		section2Task = new ConditionalStep(this, eatcookedrabbit);
//		section2Task.addStep(not(orderManual_925b2750606e45aa), pickcabbage);
//		section2Task.addStep(not(new Conditions(LogicType.OR, new VarbitRequirement(13887, Operation.EQUAL, 1, "Defeat a Chicken"), new VarbitRequirement(13910, Operation.EQUAL, 1, "Defeat 3 chickens in 6 seconds"))), attackchickenlevel1);
//		section2Task.addStep(not(orderManual_7307d7a1545249c7), feedbonestomolossus);
//		section2Task.addStep(not(new VarbitRequirement(14503, Operation.EQUAL, 1, "Pick some Sweetcorn from a Field")), picksweetcorn);
//		section2Task.addStep(not(orderManual_03a02189ef2c41c9), pickandeatonion);
//		section2Task.addStep(not(orderManual_f959773416174f78), pickwheat);
//		section2Task.addStep(not(orderManual_20f2b6f2760b4291), fillhopper);
//		section2Task.addStep(not(orderManual_7e7d7d1aa70f4206), emptyflourbin);
//		section2Task.addStep(not(orderManual_956b7e8f1cba43e0), pickpotato);
//		section2Task.addStep(not(orderManual_397839f1b1f24846), tradeharminia);
//		section2Task.addStep(not(new VarbitRequirement(15114, Operation.EQUAL, 1, "Rake a Flower Patch")), rakeflowerpatch);
//		section2Task.addStep(not(orderManual_00554878070f4f0e), emptywaterbucket);
//		section2Task.addStep(not(new VarbitRequirement(14489, Operation.EQUAL, 1, "Milk a Buffalo")), milkdairybuffalo);
//		section2Task.addStep(not(new VarbitRequirement(14507, Operation.EQUAL, 1, "Shear an Alpaca")), shearalpaca);
//		section2Task.addStep(not(orderManual_d30aa746056444c3), zanarisfairyring);
//		section2Task.addStep(not(orderManual_c75f7a1c32ef4f3f), attackcowlevel2);
//		section2Task.addStep(not(new Conditions(LogicType.OR, new VarbitRequirement(13582, Operation.EQUAL, 1, "Bury 6 bones"), new VarbitRequirement(13583, Operation.EQUAL, 1, "Bury Some Wyvern or Dragon Bones"))), burybones);
//		section2Task.addStep(not(new VarbitRequirement(14513, Operation.EQUAL, 1, "Travel to Aldarin via Fairy ring")), aldarinfairyring);
//		section2Task.addStep(not(orderManual_7060fc9ca3444a25), talktovineyardforeman);
//		section2Task.addStep(not(orderManual_b4066f8970574c8a), collectshimmeringgrapes);
//		section2Task.addStep(not(new VarbitRequirement(14623, Operation.EQUAL, 1, "Fill a Grape Barrel for the Foreman")), returntovineyardforeman);
//		section2Task.addStep(not(orderManual_04453a244b8e4e28), withdrawaldarinbanker);
//		section2Task.addStep(not(orderManual_2a4533618e3843cc), tradetoci);
//		section2Task.addStep(not(orderManual_864a7b35392e4bb5), cutextragems);
//		section2Task.addStep(not(orderManual_b1d18d00302b44e1), attackseagulllevel2);
//		section2Task.addStep(not(orderManual_39b2b856b31b46a8), tradechartership);
//		section2Task.addStep(not(orderManual_bd0d9307875d4407), cookrabbitonoven);
//
//		section3Task = new ConditionalStep(this, talktopicaria);
//		section3Task.addStep(not(orderManual_eab67f10eb07403e), talktoantonia);
//		section3Task.addStep(not(orderManual_9b1eca8dccbd42d2), fillabucketwithsand);
//
//		section4Task = new ConditionalStep(this, givestewtooli);
//		section4Task.addStep(not(orderManual_defad039d9094571), chartertocivitas);
//		section4Task.addStep(not(orderManual_52df5d410a9c4609), buyironmace);
//		section4Task.addStep(not(orderManual_71753357153f4aea), equipironmace);
//		section4Task.addStep(not(new Conditions(LogicType.OR, new VarbitRequirement(15095, Operation.EQUAL, 1, "Obtain a Casket from Fishing"), new VarbitRequirement(15373, Operation.EQUAL, 1, "Fish a House Key"))), castfishingspot);
//		section4Task.addStep(not(orderManual_2d00f499fa504f2c), talktobartender);
//		section4Task.addStep(not(new VarbitRequirement(14533, Operation.EQUAL, 1, "Drink some moon-lite")), drinkmoonlite);
//		section4Task.addStep(not(orderManual_3a1994fd479f4789), drinkjugofwine);
//		section4Task.addStep(not(new VarbitRequirement(15360, Operation.EQUAL, 1, "Successfully pickpocket a Citizen 10 times in a row")), pickpocketcitizenuntilsuccess);
//		section4Task.addStep(not(new VarbitRequirement(15113, Operation.EQUAL, 1, "Purchase a Player Owned House")), buypoh);
//		section4Task.addStep(not(new VarbitRequirement(15303, Operation.EQUAL, 1, "Sell some silk to a silk trader")), tradesilkmerchant);
//
//		section5Task = new ConditionalStep(this, returntocivitas);
//		section5Task.addStep(not(orderManual_2db5a3f19d944160), traveltoauburnvale);
//		section5Task.addStep(not(orderManual_fc2cc76a69004247), depositinauburnvale);
//		section5Task.addStep(not(orderManual_98baa1e71c7749f8), tradesebamo);
//		section5Task.addStep(not(orderManual_4aa9260549cf41b7), tradelunami);
//		section5Task.addStep(not(orderManual_dfe5b2e820144145), chopdowndeadtree);
//		section5Task.addStep(not(orderManual_b30a9b21a43c4399), makeplankatsawmill);
//		section5Task.addStep(not(orderManual_558232d615c64c3e), tanleatheratchouani);
//		section5Task.addStep(not(orderManual_b9bdb796f67b407a), tradeauburnvaleshopkeeper);
//		section5Task.addStep(not(orderManual_8bc30c12632a4f04), craftleatherchaps);
//		section5Task.addStep(not(orderManual_18df7577e9814dd7), admirebeautifullog);
//		section5Task.addStep(not(orderManual_6ec91f1a29aa464f), steponenttrail);
//		section5Task.addStep(not(new VarbitRequirement(14664, Operation.EQUAL, 1, "Pick 6 flax")), pickflax);
//		section5Task.addStep(not(orderManual_03d13e43583345cb), spinflaxandwool);
//		section5Task.addStep(not(orderManual_a1a431788a17478e), hometeleport);
//
//		ConditionalStep allSections = new ConditionalStep(this, section5Task);
//		allSections.addStep(or(not(new ZoneRequirement("In zone", new Zone(new WorldPoint(3034, 6125, 1), new WorldPoint(3037, 6128, 1)))), nor(new VarbitRequirement(14662, Operation.EQUAL, 1, "Open the Leagues Menu"), new VarbitRequirement(14445, Operation.EQUAL, 1, "Complete the Leagues Tutorial"), orderManual_b4774b5043644e3d, new VarbitRequirement(14668, Operation.EQUAL, 1, "Turn off your run"), new VarbitRequirement(14733, Operation.EQUAL, 1, "Achieve Your First Level 5"), new VarbitRequirement(14493, Operation.EQUAL, 1, "Pet Renu"), orderManual_e1bd7473bf70454e, orderManual_3742c1b9593940d1, orderManual_d874440fd5d64f29, orderManual_3e3dee13c7f04f7e, new VarbitRequirement(14441, Operation.EQUAL, 1, "Attack a dummy"), new VarbitRequirement(14528, Operation.EQUAL, 1, "Cry near a child"), orderManual_561cc210c13940ac, orderManual_6231965cb7364873, orderManual_ef2a1f04f2344ffa, new Conditions(LogicType.OR, new VarbitRequirement(14260, Operation.EQUAL, 1, "Equip 3 unique Echo Items"), new VarbitRequirement(14261, Operation.EQUAL, 1, "Equip 2 unique Echo Items")), new VarbitRequirement(13906, Operation.EQUAL, 1, "Defeat a Rat"), new VarbitRequirement(14504, Operation.EQUAL, 1, "Salute next to a statue of Quoatlos"), new VarbitRequirement(13530, Operation.EQUAL, 1, "Activate a prayer near an altar"), new VarbitRequirement(14495, Operation.EQUAL, 1, "Pet Xolo in Civitas"), new VarbitRequirement(14531, Operation.EQUAL, 1, "Drink from a bird bath"), new Conditions(LogicType.OR, new VarbitRequirement(14777, Operation.EQUAL, 1, "Chop 100 Willow Logs"), new VarbitRequirement(14778, Operation.EQUAL, 1, "Chop 100 Yew Logs"), new VarbitRequirement(14779, Operation.EQUAL, 1, "Chop 75 Magic Logs"), new VarbitRequirement(14780, Operation.EQUAL, 1, "Chop Some Logs")), orderManual_bcef081ee50848c4, new Conditions(LogicType.OR, new VarbitRequirement(14857, Operation.EQUAL, 1, "Fletch 200 Magic Longbow (u)"), new VarbitRequirement(14860, Operation.EQUAL, 1, "Fletch 50 Willow longbow (u)"), new VarbitRequirement(15075, Operation.EQUAL, 1, "Obtain 50 Million Fletching XP"), new VarbitRequirement(15322, Operation.EQUAL, 1, "Smith 150 Iron Arrowtips")), orderManual_b6371840b279439e, orderManual_33caa0d56cbf4e3a, new VarbitRequirement(14511, Operation.EQUAL, 1, "Talk to a Gladiator"), new VarbitRequirement(14666, Operation.EQUAL, 1, "Talk to any Port master"), orderManual_23938df7e41444d2, orderManual_e3d64188fe2c4386, orderManual_0643bdd0fc574df9, orderManual_b3170a80123940bc, orderManual_b4898e48afbc4790, orderManual_4ed627e87870495c, orderManual_c6d823de02b04365)), section1Task);
//		allSections.addStep(nor(orderManual_925b2750606e45aa, new Conditions(LogicType.OR, new VarbitRequirement(13887, Operation.EQUAL, 1, "Defeat a Chicken"), new VarbitRequirement(13910, Operation.EQUAL, 1, "Defeat 3 chickens in 6 seconds")), orderManual_7307d7a1545249c7, new VarbitRequirement(14503, Operation.EQUAL, 1, "Pick some Sweetcorn from a Field"), orderManual_03a02189ef2c41c9, orderManual_f959773416174f78, orderManual_20f2b6f2760b4291, orderManual_7e7d7d1aa70f4206, orderManual_956b7e8f1cba43e0, orderManual_397839f1b1f24846, new VarbitRequirement(15114, Operation.EQUAL, 1, "Rake a Flower Patch"), orderManual_00554878070f4f0e, new VarbitRequirement(14489, Operation.EQUAL, 1, "Milk a Buffalo"), new VarbitRequirement(14507, Operation.EQUAL, 1, "Shear an Alpaca"), orderManual_d30aa746056444c3, orderManual_c75f7a1c32ef4f3f, new Conditions(LogicType.OR, new VarbitRequirement(13582, Operation.EQUAL, 1, "Bury 6 bones"), new VarbitRequirement(13583, Operation.EQUAL, 1, "Bury Some Wyvern or Dragon Bones")), new VarbitRequirement(14513, Operation.EQUAL, 1, "Travel to Aldarin via Fairy ring"), orderManual_7060fc9ca3444a25, orderManual_b4066f8970574c8a, new VarbitRequirement(14623, Operation.EQUAL, 1, "Fill a Grape Barrel for the Foreman"), orderManual_04453a244b8e4e28, orderManual_2a4533618e3843cc, orderManual_864a7b35392e4bb5, orderManual_b1d18d00302b44e1, orderManual_39b2b856b31b46a8, orderManual_bd0d9307875d4407, new VarbitRequirement(13599, Operation.EQUAL, 1, "Eat a piece of food that restores at least 6 hitpoints")), section2Task);
//		allSections.addStep(nor(orderManual_eab67f10eb07403e, orderManual_9b1eca8dccbd42d2, orderManual_a695d187db0d426b), section3Task);
//		allSections.addStep(nor(orderManual_defad039d9094571, orderManual_52df5d410a9c4609, orderManual_71753357153f4aea, new Conditions(LogicType.OR, new VarbitRequirement(15095, Operation.EQUAL, 1, "Obtain a Casket from Fishing"), new VarbitRequirement(15373, Operation.EQUAL, 1, "Fish a House Key")), orderManual_2d00f499fa504f2c, new VarbitRequirement(14533, Operation.EQUAL, 1, "Drink some moon-lite"), orderManual_3a1994fd479f4789, new VarbitRequirement(15360, Operation.EQUAL, 1, "Successfully pickpocket a Citizen 10 times in a row"), new VarbitRequirement(15113, Operation.EQUAL, 1, "Purchase a Player Owned House"), new VarbitRequirement(15303, Operation.EQUAL, 1, "Sell some silk to a silk trader"), orderManual_d54c4bcf9b4a4242), section4Task);
//		return allSections;
//
//		// TODO: refine per-step requirement logic for real route progression conditions.
//	}
//
//	@Override
//	public List<ItemRequirement> getItemRequirements()
//	{
//		return List.of(bucket, pot, rake, uncutRuby, cake, knife, chisel, coins, whiteApron, greenCape, bones, grain, bucketOfWater, dramenStaff, grapeBarrel, sapphire, emerald, ruby, rawRabbit, cookedRabbit, bigFishingNet, moonLite, jugOfWine, stew, ironMace, bronzeAxe, logs, needle, thread, cowhide, leather, wool, flax);
//	}
//
//	@Override
//	public List<PanelDetails> getPanels()
//	{
//		List<PanelDetails> allSteps = new ArrayList<>();
//
//		PanelDetails section1Steps = new PanelDetails("Civitas illa Fortis", List.of(openleaguesmenu, completeleaguestutorial, claimfirstrelic, togglerunenergy, pickpocketcitizen, petrenu, bownearrenu, travelwithrenu, travelbackwithrenu, usewaterpump, attackdummy, crynearachild, stealcakesfrombakersstall, tradeshopkeeper, tradefloria, equipapronandgreencape, attackratlevel1, salutequoatlos, useprayernearshrineofralos, petxolo, drinkfrombirdbath, chopdowntree, burnlog, fletchlog, useeastcivitasbank, tradeartima, talktogladiator, talktoportmaster, talktotradercrewmember, usefurnace, depositmoltenglass, talktotradercrewmember, usefurnace, blowglassintooillanterns, depositoillanterns));
//		section1Steps.setLockingStep(section1Task);
//		allSteps.add(section1Steps);
//
//		PanelDetails section2Steps = new PanelDetails("Outer Fortis", List.of(pickcabbage, attackchickenlevel1, feedbonestomolossus, picksweetcorn, pickandeatonion, pickwheat, fillhopper, emptyflourbin, pickpotato, tradeharminia, rakeflowerpatch, emptywaterbucket, milkdairybuffalo, shearalpaca, zanarisfairyring, attackcowlevel2, burybones, aldarinfairyring, talktovineyardforeman, collectshimmeringgrapes, returntovineyardforeman, withdrawaldarinbanker, tradetoci, cutextragems, attackseagulllevel2, tradechartership, cookrabbitonoven, eatcookedrabbit));
//		section2Steps.setLockingStep(section2Task);
//		allSteps.add(section2Steps);
//
//		PanelDetails section3Steps = new PanelDetails("Sunset Coast", List.of(talktoantonia, fillabucketwithsand, talktopicaria));
//		section3Steps.setLockingStep(section3Task);
//		allSteps.add(section3Steps);
//
//		PanelDetails section4Steps = new PanelDetails("Civitas illa Fortis", List.of(chartertocivitas, buyironmace, equipironmace, castfishingspot, talktobartender, drinkmoonlite, drinkjugofwine, pickpocketcitizenuntilsuccess, buypoh, tradesilkmerchant, givestewtooli));
//		section4Steps.setLockingStep(section4Task);
//		allSteps.add(section4Steps);
//
//		PanelDetails section5Steps = new PanelDetails("Auburnvale", List.of(traveltoauburnvale, depositinauburnvale, tradesebamo, tradelunami, chopdowndeadtree, makeplankatsawmill, tanleatheratchouani, tradeauburnvaleshopkeeper, craftleatherchaps, admirebeautifullog, steponenttrail, pickflax, spinflaxandwool, hometeleport, returntocivitas));
//		section5Steps.setLockingStep(section5Task);
//		allSteps.add(section5Steps);
//
//		return allSteps;
//	}
//}
