/*
 * Copyright (c) 2026, Syrif <https://github.com/syrifgit>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.questhelper.questinfo;

import java.util.EnumMap;
import java.util.EnumSet;
import java.util.Map;

import static com.questhelper.questinfo.LeagueRegion.*;
import static com.questhelper.questinfo.QuestHelperQuest.*;

/**
 * Maps quests to the league regions required to complete them.
 * TODO: Quests with no mapping require manual curation.
 * Unmapped quests always pass the league filter.
 * Update this class per league season.
 */
public class LeagueQuestRegions
{
	private static final Map<QuestHelperQuest, EnumSet<LeagueRegion>> QUEST_REGIONS = new EnumMap<>(QuestHelperQuest.class);

	static
	{
		// F2P quests
		put(X_MARKS_THE_SPOT, ASGARNIA);
		put(THE_CORSAIR_CURSE, ASGARNIA, KANDARIN);
		put(MISTHALIN_MYSTERY, MISTHALIN);
		put(PIRATES_TREASURE, ASGARNIA);
		put(GOBLIN_DIPLOMACY, ASGARNIA);
		put(THE_KNIGHTS_SWORD, ASGARNIA);
		put(WITCHS_POTION, ASGARNIA);
		put(BLACK_KNIGHTS_FORTRESS, ASGARNIA);
		put(DORICS_QUEST, ASGARNIA);
		put(PRINCE_ALI_RESCUE, DESERT);
		put(IMP_CATCHER, MISTHALIN);
		put(VAMPYRE_SLAYER, MISTHALIN);
		put(ERNEST_THE_CHICKEN, MISTHALIN);
		put(THE_RESTLESS_GHOST, MISTHALIN);
		put(SHEEP_SHEARER, MISTHALIN);
		put(SHIELD_OF_ARRAV_PHOENIX_GANG, MISTHALIN);
		put(SHIELD_OF_ARRAV_BLACK_ARM_GANG, MISTHALIN);
		put(DEMON_SLAYER, MISTHALIN);
		put(ROMEO__JULIET, MISTHALIN);
		put(COOKS_ASSISTANT, MISTHALIN);

		// Members quests
		put(WITCHS_HOUSE, ASGARNIA);
		put(HEROES_QUEST, ASGARNIA);
		put(SCORPION_CATCHER, ASGARNIA, KANDARIN, MISTHALIN);
		put(FISHING_CONTEST, KANDARIN);
		put(TRIBAL_TOTEM, KARAMJA, KANDARIN);
		put(MONKS_FRIEND, KANDARIN);
		put(TEMPLE_OF_IKOV, KANDARIN, MISTHALIN);
		put(CLOCK_TOWER, KANDARIN);
		put(FIGHT_ARENA, KANDARIN);
		put(HAZEEL_CULT, KANDARIN);
		put(SHEEP_HERDER, KANDARIN);
		put(PLAGUE_CITY, KANDARIN);
		put(SEA_SLUG, KANDARIN);
		put(WATERFALL_QUEST, KANDARIN);
		put(OBSERVATORY_QUEST, KANDARIN);
		put(DWARF_CANNON, ASGARNIA, KANDARIN);
		put(GERTRUDES_CAT, MISTHALIN);
		put(BIG_CHOMPY_BIRD_HUNTING, KANDARIN);
		put(TAI_BWO_WANNAI_TRIO, KARAMJA);
		put(SHADES_OF_MORTTON, MORYTANIA);
		put(THRONE_OF_MISCELLANIA, FREMENNIK);
		put(HAUNTED_MINE, MORYTANIA);
		put(TROLL_ROMANCE, ASGARNIA, KANDARIN);
		put(GHOSTS_AHOY, MORYTANIA);
		put(BETWEEN_A_ROCK, ASGARNIA, FREMENNIK, KANDARIN);
		put(THE_GOLEM, DESERT);
		put(THE_GIANT_DWARF, ASGARNIA, FREMENNIK);
		put(RECRUITMENT_DRIVE, ASGARNIA);
		put(FORGETTABLE_TALE, ASGARNIA, FREMENNIK, KANDARIN);
		put(A_TAIL_OF_TWO_CATS, ASGARNIA, DESERT);
		put(WANTED, ASGARNIA, MORYTANIA, WILDERNESS);
		put(SHADOW_OF_THE_STORM, DESERT);
		put(MAKING_HISTORY, FREMENNIK, KANDARIN, MORYTANIA);
		put(SPIRITS_OF_THE_ELID, DESERT);
		put(DEVIOUS_MINDS, ASGARNIA, MORYTANIA, WILDERNESS);
		put(THE_HAND_IN_THE_SAND, ASGARNIA, KANDARIN);
		put(THE_SLUG_MENACE, ASGARNIA, KANDARIN); // also needs Misthalin OR Desert OR Wilderness for altars
		put(ELEMENTAL_WORKSHOP_II, MISTHALIN, KANDARIN);
		put(ENLIGHTENED_JOURNEY, ASGARNIA);
		put(EAGLES_PEAK, KANDARIN);
		put(ANIMAL_MAGNETISM, ASGARNIA, MORYTANIA);
		put(CONTACT, DESERT);
		put(THE_FREMENNIK_ISLES, FREMENNIK);
		put(WHAT_LIES_BELOW, DESERT, WILDERNESS);
		put(OLAFS_QUEST, FREMENNIK);
		put(ANOTHER_SLICE_OF_HAM, ASGARNIA, FREMENNIK);
		put(GRIM_TALES, ASGARNIA);
		put(BIOHAZARD, ASGARNIA, KANDARIN);
		put(TOWER_OF_LIFE, KANDARIN);
		put(LAND_OF_THE_GOBLINS, ASGARNIA, FREMENNIK, KANDARIN);
		put(ZOGRE_FLESH_EATERS, KANDARIN);
		put(CLIENT_OF_KOUREND, KOUREND);
		put(THE_QUEEN_OF_THIEVES, KOUREND);
		put(THE_DEPTHS_OF_DESPAIR, KOUREND);
		put(A_TASTE_OF_HOPE, MORYTANIA);
		put(TALE_OF_THE_RIGHTEOUS, KOUREND);
		put(THE_ASCENT_OF_ARCEUUS, KOUREND);
		put(THE_FORSAKEN_TOWER, KOUREND);
		put(THE_FREMENNIK_EXILES, FREMENNIK);
		put(SINS_OF_THE_FATHER, MORYTANIA);
		put(A_PORCINE_OF_INTEREST, ASGARNIA);
		put(GETTING_AHEAD, KOUREND);
		put(A_NIGHT_AT_THE_THEATRE, MORYTANIA);
		put(A_KINGDOM_DIVIDED, KOUREND);
		put(BENEATH_CURSED_SANDS, DESERT);
		put(SLEEPING_GIANTS, DESERT);
		put(THE_GARDEN_OF_DEATH, KOUREND);
		put(THE_PATH_OF_GLOUPHRIE, KANDARIN);
		put(CHILDREN_OF_THE_SUN, MISTHALIN);
		put(AT_FIRST_LIGHT, VARLAMORE);
		put(PERILOUS_MOON, VARLAMORE);
		put(THE_RIBBITING_TALE_OF_A_LILY_PAD_LABOUR_DISPUTE, VARLAMORE);
		put(THE_HEART_OF_DARKNESS, VARLAMORE);
		put(DEATH_ON_THE_ISLE, VARLAMORE);
		put(MEAT_AND_GREET, VARLAMORE);
		put(ETHICALLY_ACQUIRED_ANTIQUITIES, ASGARNIA, VARLAMORE);
		put(THE_FINAL_DAWN, VARLAMORE);
		put(SHADOWS_OF_CUSTODIA, VARLAMORE);
		put(SCRAMBLED, VARLAMORE);
		put(A_SOULS_BANE, MISTHALIN);
		put(RAG_AND_BONE_MAN_I, MISTHALIN, KARAMJA);
		put(ROYAL_TROUBLE, FREMENNIK);
		put(DEATH_TO_THE_DORGESHUUN, MISTHALIN);

		put(BELOW_ICE_MOUNTAIN, ASGARNIA, MISTHALIN);
		put(BIG_CHOMPY_BIRD_HUNTING, KANDARIN);
		put(CABIN_FEVER, MORYTANIA);
		put(COLD_WAR, KANDARIN, FREMENNIK);
		put(THE_CURSE_OF_ARRAV, DESERT, MISTHALIN, ASGARNIA);
		put(DARKNESS_OF_HALLOWVALE, MISTHALIN, MORYTANIA);
		put(DEFENDER_OF_VARROCK, MISTHALIN);
		put(DESERT_TREASURE, DESERT, MISTHALIN, KANDARIN, ASGARNIA, MORYTANIA);
		put(ENAKHRAS_LAMENT, DESERT);
		put(THE_FEUD, DESERT);
		put(THE_GREAT_BRAIN_ROBBERY, MORYTANIA, ASGARNIA);
		put(HORROR_FROM_THE_DEEP, FREMENNIK, KANDARIN);
		put(THE_IDES_OF_MILK, MISTHALIN);
		put(IN_AID_OF_THE_MYREQUE, MISTHALIN, MORYTANIA);
		put(IN_SEARCH_OF_THE_MYREQUE, MORYTANIA);
		put(THE_LOST_TRIBE, MISTHALIN, ASGARNIA);
		put(MAKING_FRIENDS_WITH_MY_ARM, MISTHALIN, FREMENNIK);
		put(MOUNTAIN_DAUGHTER, FREMENNIK, KANDARIN);
		put(MOURNINGS_END_PART_I, KANDARIN, TIRANNWN, ASGARNIA);
		put(MOURNINGS_END_PART_II, KANDARIN, TIRANNWN);
		put(MY_ARMS_BIG_ADVENTURE, ASGARNIA, KARAMJA);
		put(RAG_AND_BONE_MAN_II, MISTHALIN, KARAMJA, KANDARIN, ASGARNIA, MORYTANIA, DESERT);
		put(RATCATCHERS, MISTHALIN, KANDARIN, FREMENNIK, ASGARNIA, DESERT);
		put(REGICIDE, KANDARIN, TIRANNWN, ASGARNIA);
		put(ROVING_ELVES, KANDARIN, TIRANNWN);
		put(RUM_DEAL, MORYTANIA);
		put(SECRETS_OF_THE_NORTH, KANDARIN, FREMENNIK);
		put(SONG_OF_THE_ELVES, TIRANNWN, KANDARIN);
		put(TEARS_OF_GUTHIX, MISTHALIN);
		// Possibly Wilderness, but only if the abyss rcing area when tele'd there counts as wildy?
		put(TEMPLE_OF_THE_EYE, DESERT, MISTHALIN);
		put(THE_TOURIST_TRAP, DESERT);
		put(WHILE_GUTHIX_SLEEPS, MISTHALIN, ASGARNIA, KANDARIN);

		// put(TROUBLED_TORTUGANS, SEA);
		// put(PRYING_TIMES, SEA);
		// put(PANDEMONIUM, ASGARNIA, SEA);
		// put(CURRENT_AFFAIRS, KANDARIN, SEA);

		// RFD subquests
		put(RECIPE_FOR_DISASTER_START, MISTHALIN, FREMENNIK, VARLAMORE);
		put(RECIPE_FOR_DISASTER_WARTFACE_AND_BENTNOZE, MISTHALIN, ASGARNIA);
		put(RECIPE_FOR_DISASTER_DWARF, MISTHALIN, ASGARNIA, KANDARIN);
		put(RECIPE_FOR_DISASTER_EVIL_DAVE, MISTHALIN, DESERT);
		put(RECIPE_FOR_DISASTER_PIRATE_PETE, MISTHALIN, KANDARIN);
		put(RECIPE_FOR_DISASTER_LUMBRIDGE_GUIDE, MISTHALIN, ASGARNIA, KANDARIN);
		put(RECIPE_FOR_DISASTER_SIR_AMIK_VARZE, MISTHALIN, ASGARNIA, FREMENNIK);
		put(RECIPE_FOR_DISASTER_MONKEY_AMBASSADOR, MISTHALIN, KANDARIN);
		put(RECIPE_FOR_DISASTER_SKRACH_UGLOGWEE, MISTHALIN, KANDARIN);

		// Miniquests
		put(ALFRED_GRIMHANDS_BARCRAWL, KANDARIN);
		put(BARBARIAN_TRAINING, KARAMJA, KANDARIN);
		put(SKIPPY_AND_THE_MOGRES, ASGARNIA);
		put(LAIR_OF_TARN_RAZORLOR, MORYTANIA);
		put(BEAR_YOUR_SOUL, ASGARNIA, KOUREND);
		put(THE_MAGE_ARENA, WILDERNESS);
		put(FAMILY_PEST, DESERT, FREMENNIK, KANDARIN);
		put(THE_MAGE_ARENA_II, WILDERNESS);
		put(IN_SEARCH_OF_KNOWLEDGE, KOUREND);
		put(DADDYS_HOME, MISTHALIN);
		// THE_FROZEN_DOOR and INTO_THE_TOMBS don't have QuestHelperQuest entries yet
		put(HIS_FAITHFUL_SERVANTS, MORYTANIA);
		put(VALE_TOTEMS, VARLAMORE);

		// Diaries
		put(DESERT_EASY, DESERT);
		put(DESERT_MEDIUM, DESERT);
		put(DESERT_HARD, DESERT);
		put(DESERT_ELITE, DESERT);

		put(FALADOR_EASY, ASGARNIA);
		put(FALADOR_MEDIUM, ASGARNIA);
		put(FALADOR_HARD, ASGARNIA);
		put(FALADOR_ELITE, ASGARNIA);

		put(FREMENNIK_EASY, FREMENNIK);
		put(FREMENNIK_MEDIUM, FREMENNIK);
		put(FREMENNIK_HARD, FREMENNIK);
		put(FREMENNIK_ELITE, FREMENNIK);

		put(ARDOUGNE_EASY, KANDARIN);
		put(ARDOUGNE_MEDIUM, KANDARIN);
		put(ARDOUGNE_HARD, KANDARIN);
		put(ARDOUGNE_ELITE, KANDARIN);

		put(KANDARIN_EASY, KANDARIN);
		put(KANDARIN_MEDIUM, KANDARIN);
		put(KANDARIN_HARD, KANDARIN);
		put(KANDARIN_ELITE, KANDARIN);

		put(KARAMJA_EASY, KARAMJA);
		put(KARAMJA_MEDIUM, KARAMJA);
		put(KARAMJA_HARD, KARAMJA);
		put(KARAMJA_ELITE, KARAMJA);

		put(KOUREND_EASY, KOUREND);
		put(KOUREND_MEDIUM, KOUREND);
		put(KOUREND_HARD, KOUREND);
		put(KOUREND_ELITE, KOUREND);

		put(LUMBRIDGE_EASY, MISTHALIN);
		put(LUMBRIDGE_MEDIUM, MISTHALIN);
		put(LUMBRIDGE_HARD, MISTHALIN);
		put(LUMBRIDGE_ELITE, MISTHALIN);

		put(MORYTANIA_EASY, MORYTANIA);
		put(MORYTANIA_MEDIUM, MORYTANIA);
		put(MORYTANIA_HARD, MORYTANIA);
		put(MORYTANIA_ELITE, MORYTANIA);

		put(VARROCK_EASY, MISTHALIN);
		put(VARROCK_MEDIUM, MISTHALIN);
		put(VARROCK_HARD, MISTHALIN);
		put(VARROCK_ELITE, MISTHALIN);

		put(WESTERN_EASY, KANDARIN, TIRANNWN);
		put(WESTERN_MEDIUM, KANDARIN, TIRANNWN);
		put(WESTERN_HARD, KANDARIN, TIRANNWN);
		put(WESTERN_ELITE, KANDARIN, TIRANNWN);

		put(WILDERNESS_EASY, WILDERNESS);
		put(WILDERNESS_MEDIUM, WILDERNESS);
		put(WILDERNESS_HARD, WILDERNESS);
		put(WILDERNESS_ELITE, WILDERNESS);
	}

	private static void put(QuestHelperQuest quest, LeagueRegion... regions)
	{
		QUEST_REGIONS.put(quest, EnumSet.of(regions[0], regions));
	}

	public static boolean isCompletableWith(QuestHelperQuest quest, EnumSet<LeagueRegion> playerRegions)
	{
		EnumSet<LeagueRegion> required = QUEST_REGIONS.get(quest);
		if (required == null)
		{
			return false;
		}
		return playerRegions.containsAll(required);
	}
}
