package com.questhelper.questinfo;

import lombok.AllArgsConstructor;
import lombok.Getter;
import net.runelite.api.gameval.VarbitID;

@AllArgsConstructor
@Getter
public enum QuestVarbits
{
	QUEST_TAB(VarbitID.SIDE_JOURNAL_TAB),

	/**
	 * f2p Quest varbits, these don't hold the completion value.
	 */
	QUEST_BELOW_ICE_MOUNTAIN(VarbitID.BIM),
	QUEST_DEMON_SLAYER(VarbitID.DEMONSLAYER_MAIN),
	QUEST_GOBLIN_DIPLOMACY(VarbitID.GOBDIP_MAIN),
	QUEST_MISTHALIN_MYSTERY(VarbitID.MISTMYST_PROGRESS),
	QUEST_THE_CORSAIR_CURSE(VarbitID.CORSCURS_PROGRESS),
	QUEST_X_MARKS_THE_SPOT(VarbitID.CLUEQUEST),

	/**
	 * member Quest varbits, these don't hold the completion value.
	 */
	QUEST_ANIMAL_MAGNETISM(VarbitID.ANMA_MAIN),
	QUEST_BENEATH_CURSED_SANDS(VarbitID.BCS),
	QUEST_BETWEEN_A_ROCK(VarbitID.DWARFROCK_QUEST),
	QUEST_CONTACT(VarbitID.CONTACT),
	QUEST_ZOGRE_FLESH_EATERS(VarbitID.ZOGRE),
	QUEST_DARKNESS_OF_HALLOWVALE(VarbitID.MYQ3_MAIN_QUEST),
	QUEST_DEATH_TO_THE_DORGESHUUN(VarbitID.DTTD_MAIN),
	QUEST_DESERT_TREASURE(VarbitID.DESERTTREASURE),
	QUEST_DESERT_TREASURE_II(VarbitID.DT2),
	QUEST_DEVIOUS_MINDS(VarbitID.DEVIOUS_MAIN),
	QUEST_EAGLES_PEAK(VarbitID.EAGLEPEAK_QUEST),
	QUEST_ELEMENTAL_WORKSHOP_II(VarbitID.ELEMENTAL_QUEST_2_MAIN),
	QUEST_ENAKHRAS_LAMENT(VarbitID.ENAKH_QUEST),
	QUEST_ENLIGHTENED_JOURNEY(VarbitID.ZEP_QUEST),
	QUEST_THE_EYES_OF_GLOUPHRIE(VarbitID.EYEGLO_QUEST),
	QUEST_THE_PATH_OF_GLOUPHRIE(VarbitID.POG),
	QUEST_FAIRYTALE_I_GROWING_PAINS(VarbitID.FAIRY_FARMERS_QUEST),
	QUEST_FAIRYTALE_II_CURE_A_QUEEN(VarbitID.FAIRY2_QUEENCURE_QUEST),
	QUEST_THE_FEUD(VarbitID.FEUD_VAR),
	QUEST_FORGETTABLE_TALE(VarbitID.FORGET_QUEST),
	QUEST_GARDEN_OF_TRANQUILLITY(VarbitID.GARDEN_QUEST),
	QUEST_GHOSTS_AHOY(VarbitID.AHOY_QUESTVAR),
	QUEST_THE_GIANT_DWARF(VarbitID.GIANTDWARF_QUEST),
	QUEST_THE_GOLEM(VarbitID.GOLEM_A),
	QUEST_THE_HAND_IN_THE_SAND(VarbitID.HANDSAND_QUEST),
	QUEST_HORROR_FROM_THE_DEEP(VarbitID.HORRORQUEST),
	QUEST_ICTHLARINS_LITTLE_HELPER(VarbitID.ICS_LITTLE_VAR),
	QUEST_IN_AID_OF_THE_MYREQUE(VarbitID.MYREQUE_2_QUEST),
	QUEST_LAND_OF_THE_GOBLINS(VarbitID.LOTG),
	QUEST_THE_LOST_TRIBE(VarbitID.LOST_TRIBE_QUEST),
	QUEST_LUNAR_DIPLOMACY(VarbitID.LUNAR_QUEST_MAIN),
	QUEST_MAKING_HISTORY(VarbitID.MAKINGHISTORY_PROG),
	QUEST_MOUNTAIN_DAUGHTER(VarbitID.MDAUGHTER_QUEST_VAR),
	QUEST_MOURNINGS_END_PART_II(VarbitID.MOURNING_QUEST_MAIN),
	QUEST_MY_ARMS_BIG_ADVENTURE(VarbitID.MYARM),
	QUEST_RATCATCHERS(VarbitID.RATCATCH_VAR),
	QUEST_RECIPE_FOR_DISASTER(VarbitID.HUNDRED_MAIN_QUEST_VAR),
	QUEST_RECIPE_FOR_DISASTER_DWARF(VarbitID.HUNDRED_DWARF_QUEST),
	QUEST_RECIPE_FOR_DISASTER_WARTFACE_AND_BENTNOZE(VarbitID._100GOBLIN),
	QUEST_RECIPE_FOR_DISASTER_PIRATE_PETE(VarbitID._100_PIRATE_QUEST_VAR),
	QUEST_RECIPE_FOR_DISASTER_LUMBRIDGE_GUIDE(VarbitID._100GUIDE_PROG),
	QUEST_RECIPE_FOR_DISASTER_EVIL_DAVE(VarbitID.HUNDRED_DAVE_MAIN),
	QUEST_RECIPE_FOR_DISASTER_SIR_AMIK_VARZE(VarbitID.CHICKENQUEST),
	QUEST_RECIPE_FOR_DISASTER_SKRACH_UGLOGWEE(VarbitID._100_OGRE_PROG),
	QUEST_RECIPE_FOR_DISASTER_MONKEY_AMBASSADOR(VarbitID.HUNDRED_ILM_QUEST),
	QUEST_RECRUITMENT_DRIVE(VarbitID.RD_MAIN),
	QUEST_ROYAL_TROUBLE(VarbitID.ROYAL_QUEST),
	QUEST_THE_SLUG_MENACE(VarbitID.SLUG2_MAIN),
	QUEST_SHADOW_OF_THE_STORM(VarbitID.AGRITH_QUEST),
	QUEST_A_SOULS_BANE(VarbitID.SOULBANE_PROG),
	QUEST_SPIRITS_OF_THE_ELID(VarbitID.ELIDQUEST),
	QUEST_SWAN_SONG(VarbitID.SWANSONG),
	QUEST_A_TAIL_OF_TWO_CATS(VarbitID.TWOCATS_QUEST),
	QUEST_TEARS_OF_GUTHIX(VarbitID.TOG_JUNA_BOWL),
	QUEST_WANTED(VarbitID.WANTED_MAIN),
	QUEST_COLD_WAR(VarbitID.PENG_QUEST),
	QUEST_THE_FREMENNIK_ISLES(VarbitID.FRIS_QUEST),
	QUEST_TOWER_OF_LIFE(VarbitID.TOL_PROG),
	QUEST_WHAT_LIES_BELOW(VarbitID.SUROK_QUEST),
	QUEST_OLAFS_QUEST(VarbitID.OLAF_QUEST_VAR),
	QUEST_ANOTHER_SLICE_OF_HAM(VarbitID.SLICE_QUEST),
	QUEST_DREAM_MENTOR(VarbitID.DREAM_PROG),
	QUEST_GRIM_TALES(VarbitID.GRIM_QUEST),
	QUEST_KINGS_RANSOM(VarbitID.KR_QUEST),
	QUEST_MONKEY_MADNESS_II(VarbitID.MM2_PROGRESS),
	QUEST_CLIENT_OF_KOUREND(VarbitID.VEOS_PROGRESS),
	QUEST_BONE_VOYAGE(VarbitID.FOSSILQUEST_PROGRESS),
	QUEST_THE_QUEEN_OF_THIEVES(VarbitID.PISCQUEST),
	QUEST_THE_DEPTHS_OF_DESPAIR(VarbitID.HOSIDIUSQUEST),
	QUEST_DRAGON_SLAYER_II(VarbitID.DS2),
	QUEST_TALE_OF_THE_RIGHTEOUS(VarbitID.SHAYZIENQUEST),
	QUEST_A_TASTE_OF_HOPE(VarbitID.MYQ4),
	QUEST_MAKING_FRIENDS_WITH_MY_ARM(VarbitID.MY2ARM_STATUS),
	QUEST_THE_ASCENT_OF_ARCEUUS(VarbitID.ARCQUEST),
	QUEST_THE_FORSAKEN_TOWER(VarbitID.LOVAQUEST),
	QUEST_SONG_OF_THE_ELVES(VarbitID.SOTE),
	QUEST_THE_FREMENNIK_EXILES(VarbitID.VIKINGEXILE),
	QUEST_SINS_OF_THE_FATHER(VarbitID.MYQ5),
	QUEST_A_PORCINE_OF_INTEREST(VarbitID.PORCINE),
	QUEST_GETTING_AHEAD(VarbitID.GA),
	QUEST_A_KINGDOM_DIVIDED(VarbitID.AKD),
	QUEST_A_NIGHT_AT_THE_THEATRE(VarbitID.TOBQUEST),
	QUEST_TEMPLE_OF_THE_EYE(VarbitID.TOTE),
	QUEST_SLEEPING_GIANTS(VarbitID.SLEEPING_GIANTS),
	QUEST_THE_GARDEN_OF_DEATH(VarbitID.TGOD),
	QUEST_SECRETS_OF_THE_NORTH(VarbitID.SOTN),
	QUEST_CHILDREN_OF_THE_SUN(VarbitID.VMQ1),
	QUEST_DEFENDER_OF_VARROCK(VarbitID.DOV),
	QUEST_AT_FIRST_LIGHT(VarbitID.AFL),
	QUEST_PERILOUS_MOONS(VarbitID.PMOON_QUEST),
	QUEST_THE_RIBBITING_TALE_OF_A_LILY_PAD_LABOUR_DISPUTE(VarbitID.FROG_QUEST),
	QUEST_TWILIGHTS_PROMISE(VarbitID.VMQ2),
	QUEST_WHILE_GUTHIX_SLEEPS(VarbitID.WGS),
	QUEST_ETHICALLY_ACQUIRED_ANTIQUITIES(VarbitID.EAA),
	QUEST_DEATH_ON_THE_ISLE(VarbitID.DOTI),
	QUEST_MEAT_AND_GREET(VarbitID.MAG),
	QUEST_THE_HEART_OF_DARKNESS(VarbitID.VMQ3),
	QUEST_THE_CURSE_OF_ARRAV(VarbitID.COA),
	QUEST_THE_FINAL_DAWN(VarbitID.VMQ4),
	QUEST_SHADOWS_OF_CUSTODIA(VarbitID.SOC),
	QUEST_SCRAMBLED(VarbitID.SCRAMBLED),
	QUEST_TROUBLED_TORTUGANS(VarbitID.TT),
	/**
	 * mini-quest varbits, these don't hold the completion value.
	 */
	QUEST_ARCHITECTURAL_ALLIANCE(VarbitID.ZEAH_STATUE),
	QUEST_BEAR_YOUR_SOUL(VarbitID.ARCEUUS_SOULBEARER_STORY),
	QUEST_CURSE_OF_THE_EMPTY_LORD(VarbitID.SECRET_GHOST6_BACKSTORY),
	QUEST_ENCHANTED_KEY(VarbitID.MAKINGHISTORY_LOCSTATUS),
	QUEST_THE_GENERALS_SHADOW(VarbitID.SHADOW_MAJ_MAIN),
	QUEST_SKIPPY_AND_THE_MOGRES(VarbitID.SKIPPY_STATE),
	QUEST_LAIR_OF_TARN_RAZORLOR(VarbitID.LOTR_INSTANCE_ENTERED),
	QUEST_FAMILY_PEST(VarbitID.FAMILY_QUEST_PROGRESS),
	QUEST_THE_MAGE_ARENA_II(VarbitID.MA2_PROGRESS),
	QUEST_IN_SEARCH_OF_KNOWLEDGE(VarbitID.HOSDUN_KNOWLEDGE_SEARCH),
	QUEST_DADDYS_HOME(VarbitID.DADDYSHOME_STATUS),
	QUEST_HOPESPEARS_WILL(VarbitID.HOPESPEAR),
	QUEST_VALE_TOTEMS(VarbitID.ENT_TOTEMS_INTRO),
	HIS_FAITHFUL_SERVANTS(VarbitID.HFS),
	BARBARIAN_TRAINING(VarbitID.BRUT_MINIQUEST),

	// Fake miniquests
	KNIGHT_WAVES_TRAINING_GROUNDS(VarbitID.KR_KNIGHTWAVES_STATE),
	BALLOON_TRANSPORT_CRAFTING_GUILD(VarbitID.ZEP_MULTI_CRAFT),
	BALLOON_TRANSPORT_VARROCK(VarbitID.ZEP_MULTI_VARR),
	BALLOON_TRANSPORT_CASTLE_WARS(VarbitID.ZEP_MULTI_CAST),
	BALLOON_TRANSPORT_GRAND_TREE(VarbitID.ZEP_MULTI_GNO),
	STRONGHOLD_OF_SECURITY(VarbitID.SOS_EMOTE_STAMP),

	// Achievement Diaries

	// Ardougne
	ACHIEVEMENT_DIARY_ARDOUGNE_EASY(VarbitID.ARDOUGNE_EASY_REWARD),
	ACHIEVEMENT_DIARY_ARDOUGNE_MEDIUM(VarbitID.ARDOUGNE_MEDIUM_REWARD),
	ACHIEVEMENT_DIARY_ARDOUGNE_HARD(VarbitID.ARDOUGNE_HARD_REWARD),
	ACHIEVEMENT_DIARY_ARDOUGNE_ELITE(VarbitID.ARDOUGNE_ELITE_REWARD),

	// Desert
	ACHIEVEMENT_DIARY_DESERT_EASY(VarbitID.DESERT_EASY_REWARD),
	ACHIEVEMENT_DIARY_DESERT_MEDIUM(VarbitID.DESERT_MEDIUM_REWARD),
	ACHIEVEMENT_DIARY_DESERT_HARD(VarbitID.DESERT_HARD_REWARD),
	ACHIEVEMENT_DIARY_DESERT_ELITE(VarbitID.DESERT_ELITE_REWARD),

	// Falador
	ACHIEVEMENT_DIARY_FALADOR_EASY(VarbitID.FALADOR_EASY_REWARD),
	ACHIEVEMENT_DIARY_FALADOR_MEDIUM(VarbitID.FALADOR_MEDIUM_REWARD),
	ACHIEVEMENT_DIARY_FALADOR_HARD(VarbitID.FALADOR_HARD_REWARD),
	ACHIEVEMENT_DIARY_FALADOR_ELITE(VarbitID.FALADOR_ELITE_REWARD),

	// Fremennik
	ACHIEVEMENT_DIARY_FREMENNIK_EASY(VarbitID.FREMENNIK_EASY_REWARD),
	ACHIEVEMENT_DIARY_FREMENNIK_MEDIUM(VarbitID.FREMENNIK_MEDIUM_REWARD),
	ACHIEVEMENT_DIARY_FREMENNIK_HARD(VarbitID.FREMENNIK_HARD_REWARD),
	ACHIEVEMENT_DIARY_FREMENNIK_ELITE(VarbitID.FREMENNIK_ELITE_REWARD),

	// Kandarin
	ACHIEVEMENT_DIARY_KANDARIN_EASY(VarbitID.KANDARIN_EASY_REWARD),
	ACHIEVEMENT_DIARY_KANDARIN_MEDIUM(VarbitID.KANDARIN_MEDIUM_REWARD),
	ACHIEVEMENT_DIARY_KANDARIN_HARD(VarbitID.KANDARIN_HARD_REWARD),
	ACHIEVEMENT_DIARY_KANDARIN_ELITE(VarbitID.KANDARIN_ELITE_REWARD),

	// Karamja
	ACHIEVEMENT_DIARY_KARAMJA_EASY(VarbitID.ATJUN_EASY_REWARD),
	ACHIEVEMENT_DIARY_KARAMJA_MEDIUM(VarbitID.ATJUN_MED_REWARD),
	ACHIEVEMENT_DIARY_KARAMJA_HARD(VarbitID.ATJUN_HARD_REWARD),
	ACHIEVEMENT_DIARY_KARAMJA_ELITE(VarbitID.KARAMJA_ELITE_REWARD),

	// Kourend & Kebos
	ACHIEVEMENT_DIARY_KOUREND_EASY(VarbitID.KOUREND_EASY_REWARD),
	ACHIEVEMENT_DIARY_KOUREND_MEDIUM(VarbitID.KOUREND_MEDIUM_REWARD),
	ACHIEVEMENT_DIARY_KOUREND_HARD(VarbitID.KOUREND_HARD_REWARD),
	ACHIEVEMENT_DIARY_KOUREND_ELITE(VarbitID.KOUREND_ELITE_REWARD),

	// Lumbridge & Draynor
	ACHIEVEMENT_DIARY_LUMBRIDGE_EASY(VarbitID.LUMBRIDGE_EASY_REWARD),
	ACHIEVEMENT_DIARY_LUMBRIDGE_MEDIUM(VarbitID.LUMBRIDGE_MEDIUM_REWARD),
	ACHIEVEMENT_DIARY_LUMBRIDGE_HARD(VarbitID.LUMBRIDGE_HARD_REWARD),
	ACHIEVEMENT_DIARY_LUMBRIDGE_ELITE(VarbitID.LUMBRIDGE_ELITE_REWARD),

	// Morytania
	ACHIEVEMENT_DIARY_MORYTANIA_EASY(VarbitID.MORYTANIA_EASY_REWARD),
	ACHIEVEMENT_DIARY_MORYTANIA_MEDIUM(VarbitID.MORYTANIA_MEDIUM_REWARD),
	ACHIEVEMENT_DIARY_MORYTANIA_HARD(VarbitID.MORYTANIA_HARD_REWARD),
	ACHIEVEMENT_DIARY_MORYTANIA_ELITE(VarbitID.MORYTANIA_ELITE_REWARD),

	// Varrock
	ACHIEVEMENT_DIARY_VARROCK_EASY(VarbitID.VARROCK_EASY_REWARD),
	ACHIEVEMENT_DIARY_VARROCK_MEDIUM(VarbitID.VARROCK_MEDIUM_REWARD),
	ACHIEVEMENT_DIARY_VARROCK_HARD(VarbitID.VARROCK_HARD_REWARD),
	ACHIEVEMENT_DIARY_VARROCK_ELITE(VarbitID.VARROCK_ELITE_REWARD),

	// Western Provinces
	ACHIEVEMENT_DIARY_WESTERN_EASY(VarbitID.WESTERN_EASY_REWARD),
	ACHIEVEMENT_DIARY_WESTERN_MEDIUM(VarbitID.WESTERN_MEDIUM_REWARD),
	ACHIEVEMENT_DIARY_WESTERN_HARD(VarbitID.WESTERN_HARD_REWARD),
	ACHIEVEMENT_DIARY_WESTERN_ELITE(VarbitID.WESTERN_ELITE_REWARD),

	// Wilderness
	ACHIEVEMENT_DIARY_WILDERNESS_EASY(VarbitID.WILDERNESS_EASY_REWARD),
	ACHIEVEMENT_DIARY_WILDERNESS_MEDIUM(VarbitID.WILDERNESS_MEDIUM_REWARD),
	ACHIEVEMENT_DIARY_WILDERNESS_HARD(VarbitID.WILDERNESS_HARD_REWARD),
	ACHIEVEMENT_DIARY_WILDERNESS_ELITE(VarbitID.WILDERNESS_ELITE_REWARD),

	// Misc
	// TODO: Not confirmed for complete state
	CHARTING(VarbitID.SAILING_CHARTING_FULL_COMPLETION),

	CUTSCENE(VarbitID.CUTSCENE_STATUS),
	DIALOG_CHOICE(VarbitID.SETTINGS_BARBARIAN_POTION_MAKEX);

	private final int id;
}
