name: Build with Snapshot RuneLite
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build using latest runelite snapshot version
        run: ./gradlew --refresh-dependencies -Puse.snapshot clean build -x test
